import { useState } from "react";
import { Link } from "react-router-dom";
import SeoHead from "../../components/SeoHead";
import ShareButtons from "../../components/ShareButtons";
import DoAideFooter from "../../components/DoAideFooter";
import RelatedTools from "../../components/RelatedTools";
import ToolsNav from "../../components/ToolsNav";
import { usePageTitle } from "../../hooks/usePageTitle";

const FAQ_ITEMS = [
  {
    q: "What is the threshold value for generating an e-way bill?",
    a: "An e-way bill must be generated when the value of goods being transported exceeds ₹50,000. However, for interstate movement of handicraft goods and goods sent for job work, an e-way bill is required regardless of value.",
  },
  {
    q: "Who should generate the e-way bill?",
    a: "The e-way bill can be generated by the consignor (supplier), the consignee (recipient), or the transporter. If the supplier is unregistered, the transporter or the recipient must generate it.",
  },
  {
    q: "What is the validity of an e-way bill?",
    a: "For regular vehicles: 1 day per 200 km or part thereof. For over-dimensional cargo: 1 day per 100 km. Validity can be extended before expiry if goods cannot reach the destination in time.",
  },
  {
    q: "Can an e-way bill be cancelled?",
    a: "Yes, an e-way bill can be cancelled within 24 hours of generation, provided the goods have not been verified in transit by a proper officer. After 24 hours, it cannot be cancelled.",
  },
  {
    q: "Is an e-way bill required for goods transported within the same city?",
    a: "If the value exceeds ₹50,000, yes. However, many states have exempted intra-city movements or movements within a specified distance (e.g., 10 km). Check your state's specific rules.",
  },
  {
    q: "What happens if goods are transported without an e-way bill?",
    a: "The goods and vehicle can be detained or seized. A penalty of ₹10,000 or the tax sought to be evaded (whichever is greater) may be imposed. Release requires payment of penalty and tax.",
  },
  {
    q: "Do I need an e-way bill for goods sent for job work?",
    a: "Yes. An e-way bill is required for movement of goods to a job worker, even if the value is less than ₹50,000. The principal or the registered job worker can generate it.",
  },
  {
    q: "Is an e-way bill needed for goods exempt from GST?",
    a: "Generally, no. Exempt goods listed in Annexure A of Rule 138(14) — such as fruits, vegetables, milk, eggs, and certain specified goods — do not require an e-way bill even if the value exceeds ₹50,000.",
  },
];

const HOWTO_SCHEMA = {
  "@context": "https://schema.org",
  "@type": "HowTo",
  name: "How to Generate an E-Way Bill",
  description: "Step-by-step guide to generating an e-way bill on the e-way bill portal",
  step: [
    { "@type": "HowToStep", name: "Register on the Portal", text: "Visit ewaybillgst.gov.in and register using your GSTIN." },
    { "@type": "HowToStep", name: "Log In", text: "Log in with your username and password on the e-way bill portal." },
    { "@type": "HowToStep", name: "Select Generate New", text: "Go to E-Way Bill > Generate New from the left menu." },
    { "@type": "HowToStep", name: "Enter Transaction Details", text: "Select transaction type (Outward/Inward), sub-type, and document details (invoice number, date)." },
    { "@type": "HowToStep", name: "Enter From/To Details", text: "Enter supplier GSTIN and address, recipient GSTIN and delivery address with PIN codes." },
    { "@type": "HowToStep", name: "Add Item Details", text: "Enter product name, HSN code, quantity, taxable value, and GST rate for each item." },
    { "@type": "HowToStep", name: "Enter Transport Details", text: "Enter transporter name, transporter ID (GSTIN), vehicle number, and mode of transport." },
    { "@type": "HowToStep", name: "Submit and Generate", text: "Review all details and click Submit. The system generates a unique 12-digit EWB number." },
  ],
};

const FAQ_SCHEMA = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: FAQ_ITEMS.map((item) => ({
    "@type": "Question",
    name: item.q,
    acceptedAnswer: { "@type": "Answer", text: item.a },
  })),
};

const BREADCRUMBS = [
  { name: "Home", url: "https://gst.doaide.com" },
  { name: "Guides", url: "https://gst.doaide.com/guides" },
  { name: "E-Way Bill Guide" },
];

function FaqSection() {
  const [openIndex, setOpenIndex] = useState(null);
  return (
    <section aria-labelledby="faq-heading">
      <h2 id="faq-heading">Frequently Asked Questions</h2>
      <dl className="compare-faq-list">
        {FAQ_ITEMS.map((item, i) => (
          <div key={i} className="compare-faq-item">
            <dt>
              <button
                className="compare-faq-q"
                aria-expanded={openIndex === i}
                onClick={() => setOpenIndex(openIndex === i ? null : i)}
              >
                {item.q}
                <span aria-hidden="true">{openIndex === i ? "−" : "+"}</span>
              </button>
            </dt>
            {openIndex === i && <dd className="compare-faq-a">{item.a}</dd>}
          </div>
        ))}
      </dl>
    </section>
  );
}

export default function EwayBillGuide() {
  usePageTitle("Complete E-Way Bill Guide for Businesses — Rules & Generation");

  return (
    <div className="tool-page">
      <SeoHead
        title="Complete E-Way Bill Guide for Businesses — Rules, Generation & Validity"
        description="Everything about e-way bills under GST. Learn when to generate, validity periods, exemptions, penalties, and step-by-step generation process. Updated for 2026."
        path="/guides/eway-bill"
        jsonLd={[HOWTO_SCHEMA, FAQ_SCHEMA]}
        breadcrumbs={BREADCRUMBS}
      />
      <ToolsNav />
      <main className="tool-main">
        <div className="tool-container" style={{ maxWidth: 800 }}>
          <h1 className="tool-title">Complete E-Way Bill Guide for Businesses</h1>
          <p className="tool-subtitle">
            Everything you need to know about e-way bills — when they're required,
            how to generate them, validity rules, and penalties. Updated for 2026.
          </p>

          <ShareButtons path="/guides/eway-bill" text="Complete e-way bill guide for businesses under GST — DoAide GST" />

          <nav className="blog-toc" aria-label="Table of contents">
            <h2>Contents</h2>
            <ol>
              <li><a href="#what-is">What is an E-Way Bill?</a></li>
              <li><a href="#when-required">When is it Required?</a></li>
              <li><a href="#who-generates">Who Should Generate It?</a></li>
              <li><a href="#how-to-generate">How to Generate an E-Way Bill</a></li>
              <li><a href="#validity">Validity & Extension</a></li>
              <li><a href="#exemptions">Exemptions</a></li>
              <li><a href="#penalties">Penalties for Non-Compliance</a></li>
              <li><a href="#consolidated">Consolidated E-Way Bill</a></li>
              <li><a href="#state-rules">State-Specific Rules</a></li>
              <li><a href="#faq-heading">FAQs</a></li>
            </ol>
          </nav>

          <article className="blog-content">
            <section id="what-is">
              <h2>What is an E-Way Bill?</h2>
              <p>
                An E-Way Bill (Electronic Way Bill) is a digital document required under GST
                for the movement of goods worth more than ₹50,000. It is generated on the
                e-way bill portal (<strong>ewaybillgst.gov.in</strong>) and serves as proof
                that GST has been paid (or will be paid) on the goods being transported.
              </p>
              <p>
                The e-way bill system was introduced under the GST regime to replace the
                earlier state-wise waybill systems, creating a unified national system for
                tracking the movement of goods.
              </p>
            </section>

            <section id="when-required">
              <h2>When is an E-Way Bill Required?</h2>
              <p>An e-way bill must be generated when:</p>
              <ul>
                <li>Goods worth more than <strong>₹50,000</strong> are transported — whether it's a sale, purchase, return, or transfer</li>
                <li><strong>Interstate movement</strong> of handicraft goods by exempted dealers — any value</li>
                <li>Goods sent for <strong>job work</strong> — regardless of consignment value</li>
                <li>Movement of goods by <strong>principal to job worker</strong> in another state — any value</li>
              </ul>
              <p>
                The ₹50,000 threshold applies to a single consignment (all goods in one
                conveyance going to one recipient from one supplier), not individual invoices.
              </p>
            </section>

            <section id="who-generates">
              <h2>Who Should Generate the E-Way Bill?</h2>
              <ul>
                <li><strong>Registered supplier (consignor):</strong> when goods are sent to a registered or unregistered buyer</li>
                <li><strong>Registered recipient (consignee):</strong> when goods are received from an unregistered supplier</li>
                <li><strong>Transporter:</strong> when neither supplier nor recipient generates it, or when they are unregistered</li>
              </ul>
              <p>
                In practice, the supplier generates Part A (invoice details) and the transporter
                fills Part B (vehicle details). The e-way bill is valid only when both parts
                are complete.
              </p>
            </section>

            <section id="how-to-generate">
              <h2>How to Generate an E-Way Bill — Step by Step</h2>
              <ol>
                <li>
                  <strong>Register on the portal:</strong> Visit <em>ewaybillgst.gov.in</em> and
                  register using your GSTIN. First-time users get a username and password.
                </li>
                <li>
                  <strong>Log in and select "Generate New":</strong> Navigate to E-Way Bill →
                  Generate New from the menu.
                </li>
                <li>
                  <strong>Select transaction type:</strong> Outward (for sales/dispatches) or
                  Inward (for purchases/receipts). Select the sub-type (supply, export, job work, etc.).
                </li>
                <li>
                  <strong>Enter document details:</strong> Invoice number, invoice date, and
                  the value of goods.
                </li>
                <li>
                  <strong>Enter supplier and recipient details:</strong> GSTIN, trade name,
                  and addresses with PIN codes for both parties.
                </li>
                <li>
                  <strong>Add item details:</strong> Product name, HSN code, quantity, unit,
                  taxable value, and applicable GST rate.
                </li>
                <li>
                  <strong>Enter transport details (Part B):</strong> Transporter name, transporter
                  ID (GSTIN), vehicle number, and mode of transport (road, rail, air, or ship).
                </li>
                <li>
                  <strong>Submit:</strong> Review and submit. A unique 12-digit E-Way Bill
                  Number (EBN) is generated, along with a QR code.
                </li>
              </ol>
            </section>

            <section id="validity">
              <h2>E-Way Bill Validity & Extension</h2>
              <table className="due-date-table" style={{ marginBottom: "1rem" }}>
                <thead>
                  <tr>
                    <th>Type of Conveyance</th>
                    <th>Distance</th>
                    <th>Validity</th>
                  </tr>
                </thead>
                <tbody>
                  <tr><td>Regular vehicle</td><td>Up to 200 km</td><td>1 day</td></tr>
                  <tr><td>Regular vehicle</td><td>200–400 km</td><td>2 days</td></tr>
                  <tr><td>Regular vehicle</td><td>400–600 km</td><td>3 days</td></tr>
                  <tr><td>Over-dimensional cargo</td><td>Up to 100 km</td><td>1 day</td></tr>
                  <tr><td>Over-dimensional cargo</td><td>100–200 km</td><td>2 days</td></tr>
                </tbody>
              </table>
              <p>
                Validity starts from the date and time of generation. If goods cannot reach
                the destination within the validity period, the generator or transporter can
                extend it <strong>before expiry</strong> by updating the reason and expected
                time of arrival. Extensions are allowed within 8 hours before or after expiry.
              </p>
            </section>

            <section id="exemptions">
              <h2>Exemptions from E-Way Bill</h2>
              <p>An e-way bill is NOT required for:</p>
              <ul>
                <li>Goods transported by non-motorized conveyance (bullock cart, hand cart, etc.)</li>
                <li>Goods transported from port, airport, or land customs station to an ICD or CFS for customs clearance</li>
                <li>Goods under customs supervision or customs seal</li>
                <li>Transit cargo from or to Nepal or Bhutan</li>
                <li>Defence or military equipment under the Ministry of Defence</li>
                <li>Empty cargo containers</li>
                <li>Postal bags carried by the Department of Posts</li>
                <li>Natural or cultured pearls and precious stones</li>
                <li>Jewellery, goldsmiths' wares, and coins</li>
                <li>Used personal and household effects</li>
                <li>Coral (unworked and worked)</li>
              </ul>
              <h3>GST-Exempt Goods (Annexure A)</h3>
              <ul>
                <li>Fresh fruits, vegetables, milk, eggs, unprocessed food grains</li>
                <li>LPG for household use, kerosene under PDS</li>
                <li>Currency, stamps, judicial papers</li>
                <li>Newspapers, books, periodicals</li>
              </ul>
            </section>

            <section id="penalties">
              <h2>Penalties for Non-Compliance</h2>
              <ul>
                <li>
                  <strong>Goods and vehicle detained:</strong> if goods are transported without
                  a valid e-way bill or with an expired one.
                </li>
                <li>
                  <strong>Penalty:</strong> ₹10,000 or the tax sought to be evaded, whichever
                  is greater (Section 129 of CGST Act).
                </li>
                <li>
                  <strong>Release:</strong> goods and vehicle are released upon payment of
                  applicable tax and penalty equal to 200% of the tax amount (for taxable goods)
                  or 50% of the value of exempt goods.
                </li>
                <li>
                  <strong>Prosecution:</strong> for repeated offences, the penalty may include
                  prosecution under Section 132.
                </li>
              </ul>
            </section>

            <section id="consolidated">
              <h2>Consolidated E-Way Bill</h2>
              <p>
                When a transporter carries multiple consignments in a single vehicle, they can
                generate a <strong>Consolidated E-Way Bill (CEWB)</strong> instead of carrying
                individual e-way bills. The CEWB bundles multiple EWBs into a single document
                with one consolidated EWB number.
              </p>
              <p>
                This is useful for LTL (less-than-truckload) carriers and courier companies
                who handle multiple shipments per trip.
              </p>
            </section>

            <section id="state-rules">
              <h2>State-Specific Rules</h2>
              <p>
                Several states have introduced their own thresholds and rules:
              </p>
              <ul>
                <li><strong>Karnataka:</strong> E-way bill required for goods worth ₹50,000+ for intrastate movement</li>
                <li><strong>Kerala:</strong> State portal for intrastate movement; threshold ₹50,000</li>
                <li><strong>Delhi:</strong> E-way bill required for goods worth ₹1,00,000+ for intrastate movement (higher threshold)</li>
                <li><strong>Uttar Pradesh:</strong> Certain goods require e-way bill even below ₹50,000 (tobacco, pan masala)</li>
              </ul>
              <p>
                Always check your state's GST department notifications for the latest rules.
              </p>
            </section>

            <FaqSection />

            <section className="compare-cta" style={{ marginTop: "2rem" }}>
              <h2>Check if Your Shipment Needs an E-Way Bill</h2>
              <p>
                Use our free E-Way Bill Checker to instantly verify if your consignment
                requires an e-way bill. No sign-up needed.
              </p>
              <div className="compare-cta-buttons">
                <Link to="/eway-bill" className="btn btn-primary">Check E-Way Bill Requirement</Link>
                <Link to="/calculator" className="btn compare-cta-secondary">GST Calculator</Link>
              </div>
            </section>
          </article>

          <RelatedTools current="/guides/eway-bill" />
        </div>
      </main>
      <DoAideFooter />
    </div>
  );
}
