"""Contract checks over the assembled route table.

These are not tests of business behaviour. They are guards against two ways
FastAPI silently misreads the code we write, both of which have bitten this
codebase and neither of which shows up as a failure in the router's own tests:

1.  ``from __future__ import annotations`` turns ``-> None`` into the NoneType
    *class*, which FastAPI reads as a real response model. On a 204 that trips
    an assertion at import time and the whole app stops booting.

2.  FastAPI resolves string annotations against ``call.__globals__``. A
    callable-class dependency has no ``__globals__``, so its ``request:
    Request`` parameter stays an unresolved ForwardRef, and FastAPI quietly
    reclassifies it as a required *query parameter*. Every route carrying that
    dependency then 422s — including register and login.

Both failures are structural, so the checks sweep every route rather than
naming the ones that happen to be wrong today.

Sweeping is itself the fragile part, and it has already broken once: see
``app.core.routes`` for why ``app.routes`` is not the list it looks like.
"""
from __future__ import annotations

from io import BytesIO

import pytest
from fastapi import Request
from fastapi.dependencies.utils import get_dependant, get_typed_signature
from starlette.status import HTTP_204_NO_CONTENT, HTTP_304_NOT_MODIFIED

from app.core import params
from app.core.rate_limit import RateLimit
from app.core.routes import collect_api_routes
from app.main import app
from app.services import gst_calendar
from tests.conftest import SUPPLIER_GSTIN_SAME_STATE, TEST_EMAIL, TEST_PASSWORD

# Statuses RFC 9110 forbids a body on. FastAPI asserts on these at import.
BODYLESS_STATUSES = {HTTP_204_NO_CONTENT, HTTP_304_NOT_MODIFIED, 100, 101, 102, 103}

# Routes that must appear in any correct sweep, one per router. If the walk
# below silently stops descending again, these name what went missing instead
# of leaving a count to be argued about.
EXPECTED_PATHS = frozenset(
    {
        "/api/v1/health",
        "/api/v1/auth/login",
        "/api/v1/invoices",
        "/api/v1/dashboard",
        "/api/v1/reconciliation/run",
        "/api/v1/itc",
        "/api/v1/filing/validate",
        "/api/v1/filing/{return_type}/filed",
        "/api/v1/suppliers",
        "/api/v1/alerts",
    }
)


# The walk moved to ``app.core.routes`` when app code needed it too: the
# OpenAPI customisation derives 401 and 429 from the same assembled table these
# sweeps read, and two copies of a walk this easy to get silently wrong is one
# too many. The reasoning that used to live here is in that module's docstring.
API_ROUTES = collect_api_routes(app)


def _route_id(route) -> str:
    return f"{','.join(sorted(route.methods))} {route.path}"


def _upload(client, text: str, *, name: str = "bill.txt") -> int:
    """Upload one invoice and return its id. Mirrors tests/test_invoices.py."""
    response = client.post(
        "/api/v1/invoices/upload",
        files={"file": (name, BytesIO(text.encode()), "text/plain")},
        data={"invoice_type": "purchase"},
    )
    assert response.status_code == 201, response.text
    return response.json()["invoice"]["id"]


@pytest.fixture(scope="module")
def routes():
    # If this is ever empty the sweeps below would pass vacuously.
    assert API_ROUTES, "no APIRoutes registered — the sweeps would prove nothing"
    return API_ROUTES


class TestTheAppAssembles:
    def test_the_route_table_is_populated(self, routes):
        assert len(routes) > 20

    def test_the_sweep_reaches_every_included_router(self, routes):
        # The count above notices a sweep that collapses to nothing. This
        # notices one that reaches some routers and not others — the shape a
        # half-working walk over a nested route tree actually takes.
        missing = sorted(EXPECTED_PATHS - {route.path for route in routes})
        assert missing == [], "the sweep never reached: " + ", ".join(missing)

    def test_the_sweep_agrees_with_the_published_schema(self, routes):
        # Independent cross-check: OpenAPI is generated by FastAPI's own walk
        # of the tree, so it catches this file's walk drifting from it.
        swept = {route.path for route in routes if route.include_in_schema}
        assert swept == set(app.openapi()["paths"])

    def test_every_route_has_a_unique_method_and_path(self, routes):
        seen = [(_route_id(route)) for route in routes]
        assert len(seen) == len(set(seen)), "two routes claim the same method and path"


class TestBodylessStatusCodes:
    """A 204 must not declare a response model, however indirectly."""

    def test_no_bodyless_route_declares_a_response_model(self, routes):
        offenders = [
            _route_id(route)
            for route in routes
            if route.status_code in BODYLESS_STATUSES and route.response_model
        ]
        assert offenders == [], (
            "these routes return a bodyless status but declare a response model — "
            "pass response_model=None explicitly: " + ", ".join(offenders)
        )

    def test_a_bodyless_route_returns_no_content(self, auth_client, sample_invoice_text):
        # The delete route is the live example of the pattern above; prove the
        # contract end to end rather than only in the route table.
        invoice_id = _upload(auth_client, sample_invoice_text)

        response = auth_client.delete(f"/api/v1/invoices/{invoice_id}")
        assert response.status_code == 204
        assert response.content == b""

    def test_the_deleted_invoice_is_gone_from_the_listing(self, auth_client, sample_invoice_text):
        invoice_id = _upload(auth_client, sample_invoice_text)
        auth_client.delete(f"/api/v1/invoices/{invoice_id}")

        listing = auth_client.get("/api/v1/invoices")
        assert invoice_id not in [row["id"] for row in listing.json()["items"]]


class TestDependencyAnnotationsResolve:
    """No dependency may leak an unresolved annotation into the query string."""

    def test_the_rate_limit_dependency_sees_a_real_request(self):
        # The direct regression: with postponed evaluation on, this parameter
        # comes back as ForwardRef('Request') and FastAPI makes it a query arg.
        signature = get_typed_signature(RateLimit("probe", "5/minute"))
        annotation = signature.parameters["request"].annotation
        assert annotation is Request, f"expected Request, got {annotation!r}"

    def test_a_callable_class_dependency_has_no_globals_to_resolve_against(self):
        # Documents *why* the fix is what it is: were this to gain __globals__
        # in a future FastAPI, the future-import could go back.
        assert not hasattr(RateLimit("probe", "5/minute"), "__globals__")

    def test_no_route_takes_a_query_parameter_named_request(self, routes):
        offenders = [
            _route_id(route)
            for route in routes
            if any(param.name == "request" for param in route.dependant.query_params)
        ]
        assert offenders == [], (
            "'request' surfaced as a query parameter — a dependency's Request "
            "annotation failed to resolve on: " + ", ".join(offenders)
        )

    def test_no_route_has_an_unresolved_forward_ref_anywhere(self, routes):
        offenders = []
        for route in routes:
            for param in (
                route.dependant.query_params
                + route.dependant.path_params
                + route.dependant.header_params
                + route.dependant.cookie_params
            ):
                if isinstance(param.field_info.annotation, str) or "ForwardRef" in repr(
                    param.field_info.annotation
                ):
                    offenders.append(f"{_route_id(route)}:{param.name}")
        assert offenders == [], "unresolved annotations: " + ", ".join(offenders)

    def test_every_rate_limited_route_still_resolves_its_dependencies(self, routes):
        # get_dependant re-walks the tree the way startup does; a dependency
        # that cannot be introspected raises here rather than at request time.
        for route in routes:
            dependant = get_dependant(path=route.path_format, call=route.endpoint)
            assert dependant is not None


class TestRateLimitedRoutesAcceptPlainRequests:
    """The user-visible shape of bug 2: a 422 asking for a 'request' field."""

    def test_register_does_not_demand_a_request_query_parameter(self, client):
        response = client.post(
            "/api/v1/auth/register",
            json={
                "email": "contract@example.com",
                "password": "Sufficiently-Long-Pass1",
                "gstin": SUPPLIER_GSTIN_SAME_STATE,
                "legal_name": "Contract Test Private Limited",
                "trade_name": "Contract Test",
                "full_name": "Contract Tester",
            },
        )
        assert response.status_code == 201, response.text

    def test_login_does_not_demand_a_request_query_parameter(self, client, auth_client):
        # Login is the OAuth2 password form, so the credentials go as form data.
        response = client.post(
            "/api/v1/auth/login",
            data={"username": TEST_EMAIL, "password": TEST_PASSWORD},
        )
        assert response.status_code == 200, response.text

    def test_a_validation_error_names_a_real_field(self, client):
        # Before the fix the 422 pointed at ["query", "request"], which is not
        # a field any caller can supply — the error was unactionable.
        response = client.post("/api/v1/auth/login", data={"username": "nobody@example.com"})
        assert response.status_code == 422
        locations = [detail["loc"] for detail in response.json()["detail"]]
        assert ["query", "request"] not in locations
        assert all("request" not in location for location in locations)


class TestEndpointSignatures:
    """Cheap sweeps that catch copy-paste mistakes across the routers."""

    def test_every_published_route_carries_a_summary_for_the_docs(self, routes):
        # Only routes that actually reach /docs are held to this. The redirect
        # at "/" is include_in_schema=False and has no reader to document for.
        missing = [
            _route_id(route)
            for route in routes
            if route.include_in_schema and not (route.summary or route.description)
        ]
        assert missing == [], "undocumented routes: " + ", ".join(missing)

    def test_the_openapi_schema_builds(self):
        # Generating the schema walks every response model, so a model that is
        # unserialisable fails here rather than the first time someone opens
        # /docs in production.
        schema = app.openapi()
        assert schema["openapi"].startswith("3.")
        assert schema["paths"]


class TestEveryPeriodParameterNamesARealMonth:
    """A filing period is ``YYYY-MM``, and the month has to exist.

    Every route here once validated one with ``\\d{4}-\\d{2}``, which is a
    shape check and not a period check: it accepts ``2026-00`` and ``2026-13``.
    Those reach arithmetic that assumes a real month — ``next_period("2026-13")``
    is ``2026-14``, which ``date()`` refuses — so the dashboard answered a
    malformed query string with a 500, and the filing previews answered with a
    200 carrying a GSTR-1 stamped ``fp=132026``.

    Swept rather than spot-checked because the failure mode is a new route
    spelling the pattern out by hand again, which no individual route's tests
    would notice.
    """

    @staticmethod
    def _period_schemas(route) -> list[dict]:
        """Every ``period`` parameter's schema on *route*, query or path."""
        dependant = route.dependant
        found = []
        for param in (*dependant.query_params, *dependant.path_params):
            if param.name != "period":
                continue
            schema = param.field_info
            found.append(schema)
        return found

    def test_at_least_one_route_takes_a_period(self):
        # Guards the sweep itself: a collector that finds nothing passes every
        # assertion below without checking anything.
        total = sum(
            len(self._period_schemas(route))
            for route in collect_api_routes(app)
            if hasattr(route, "dependant")
        )
        assert total >= 10, f"only found {total} period parameters — sweep is broken"

    def test_every_period_parameter_carries_the_canonical_pattern(self):
        offenders = []
        for route in collect_api_routes(app):
            if not hasattr(route, "dependant"):
                continue
            for field_info in self._period_schemas(route):
                patterns = [
                    getattr(meta, "pattern", None)
                    for meta in getattr(field_info, "metadata", []) or []
                ]
                if gst_calendar.PERIOD_PATTERN not in patterns:
                    offenders.append((route.path, patterns))
        assert not offenders, (
            "these period parameters do not use gst_calendar.PERIOD_PATTERN: "
            f"{offenders}"
        )

    @pytest.mark.parametrize(
        "period", ["2026-00", "2026-13", "2026-99", "0000-01", "9999-12", "2017-06"]
    )
    @pytest.mark.parametrize(
        "url",
        [
            "/api/v1/dashboard",
            "/api/v1/invoices",
            "/api/v1/itc",
            "/api/v1/alerts",
            "/api/v1/reconciliation",
            "/api/v1/reconciliation/latest",
            "/api/v1/reconciliation/gstr2b/2026-13",
            "/api/v1/filing/validate",
            "/api/v1/filing/gstr1",
            "/api/v1/filing/gstr3b",
        ],
    )
    def test_an_impossible_month_is_refused_not_answered(
        self, auth_client, url, period
    ):
        response = auth_client.get(url, params={"period": period})
        assert response.status_code == 422, (
            f"{url} answered {response.status_code} for period={period}"
        )

    @pytest.mark.parametrize("period", ["2026-00", "2026-13"])
    def test_a_reconciliation_cannot_be_run_for_a_month_that_does_not_exist(
        self, auth_client, period
    ):
        assert (
            auth_client.post(
                "/api/v1/reconciliation/run", json={"period": period}
            ).status_code
            == 422
        )

    def test_a_real_month_is_still_accepted(self, auth_client):
        # The guard against over-correcting into refusing everything.
        assert auth_client.get(
            "/api/v1/dashboard", params={"period": "2026-04"}
        ).status_code == 200


class TestEveryBareIntegerInAUrlIsBounded:
    """``invoice_id: int`` and ``offset: int`` look validated and are not.

    Python's ``int`` has no width. FastAPI coerces the digits and hands them
    on, so the request finally fails at the database — differently on each
    backend, and neither answer is the one the caller has earned:

    *   ``OFFSET 10000000000000000000000000`` is ``bigint out of range`` on
        Postgres and ``OverflowError: Python int too large to convert to SQLite
        INTEGER`` here. A 500 either way, from a query string, on four list
        endpoints — the cheapest denial of service in the product.
    *   ``WHERE id = <the same>`` raises that ``OverflowError`` on SQLite and
        quietly matches nothing on Postgres. So the id case is a 500 in the
        suite and a 404 on the deployment: the split that hides a defect
        rather than showing it, in the direction that makes the *tests* look
        like the broken thing.

    Bounded once in ``app.core.params`` rather than at each of the twelve call
    sites, which is what makes it sweepable: a route added later inherits the
    bound by spelling its parameter with those names, and the sweep below is
    what notices when it doesn't.
    """

    # Names a bound is required on. ``limit`` is deliberately absent: every
    # list already caps it with an explicit ``le``, and the sweep asserts that
    # separately rather than assuming it.
    ID_SUFFIX = "_id"
    PAGING_NAMES = frozenset({"offset", "limit"})

    def _int_params(self, route):
        """Every path or query parameter this route reads as a bare int."""
        found = []
        for param in (*route.dependant.query_params, *route.dependant.path_params):
            annotation = param.field_info.annotation
            if annotation is not int:
                continue
            found.append((param.name, param.field_info))
        return found

    def _ceiling(self, field_info):
        for meta in getattr(field_info, "metadata", []) or []:
            if (value := getattr(meta, "le", None)) is not None:
                return value
            if (value := getattr(meta, "lt", None)) is not None:
                return value - 1
        return None

    def _floor(self, field_info):
        for meta in getattr(field_info, "metadata", []) or []:
            if (value := getattr(meta, "ge", None)) is not None:
                return value
            if (value := getattr(meta, "gt", None)) is not None:
                return value + 1
        return None

    def test_the_sweep_finds_the_parameters_it_is_checking(self):
        # A collector that finds nothing passes everything below.
        names = {
            name
            for route in collect_api_routes(app)
            if hasattr(route, "dependant")
            for name, _ in self._int_params(route)
        }
        assert "offset" in names and any(n.endswith("_id") for n in names), names

    def test_every_row_id_in_a_path_is_bounded(self):
        offenders = []
        for route in collect_api_routes(app):
            if not hasattr(route, "dependant"):
                continue
            for param in route.dependant.path_params:
                if not param.name.endswith(self.ID_SUFFIX):
                    continue
                if param.field_info.annotation is not int:
                    continue
                if self._ceiling(param.field_info) is None:
                    offenders.append(f"{route.path}:{param.name}")
        assert not offenders, (
            "these path ids take an integer of any width — spell them "
            f"``app.core.params.RowId``: {offenders}"
        )

    def test_every_pagination_parameter_is_bounded(self):
        offenders = []
        for route in collect_api_routes(app):
            if not hasattr(route, "dependant"):
                continue
            for name, field_info in self._int_params(route):
                if name not in self.PAGING_NAMES:
                    continue
                if self._ceiling(field_info) is None:
                    offenders.append(f"{route.path}:{name}")
        assert not offenders, (
            "these paging parameters take an integer of any width — spell an "
            f"offset ``app.core.params.Offset``: {offenders}"
        )

    def test_every_row_id_in_a_path_has_a_floor_too(self):
        # A ceiling alone is only half a bound. ``le`` is satisfied by every
        # negative number, so an id wide enough to overflow the column reached
        # the lookup anyway as long as it was negative.
        offenders = []
        for route in collect_api_routes(app):
            if not hasattr(route, "dependant"):
                continue
            for param in route.dependant.path_params:
                if not param.name.endswith(self.ID_SUFFIX):
                    continue
                if param.field_info.annotation is not int:
                    continue
                if self._floor(param.field_info) is None:
                    offenders.append(f"{route.path}:{param.name}")
        assert not offenders, (
            "these path ids accept any negative integer — spell them "
            f"``app.core.params.RowId``: {offenders}"
        )

    def test_the_floor_is_the_lowest_id_a_row_could_have(self):
        # Every primary key here is an autoincrementing Integer, so the
        # sequence starts at 1 and nothing at or below zero names a row.
        assert params.MIN_ID == 1
        for route in collect_api_routes(app):
            if not hasattr(route, "dependant"):
                continue
            for param in route.dependant.path_params:
                if not param.name.endswith(self.ID_SUFFIX):
                    continue
                if param.field_info.annotation is not int:
                    continue
                floor = self._floor(param.field_info)
                assert floor is not None and floor >= params.MIN_ID, (
                    f"{route.path}:{param.name} allows {floor}"
                )

    def test_the_ceiling_is_one_a_row_id_could_actually_reach(self):
        # A bound that is merely *some* number would still hand the database a
        # value it cannot hold. Every id in this schema is an ``Integer``, so
        # 2**31-1 is both the largest id that can exist and comfortably inside
        # what an OFFSET clause accepts.
        assert params.MAX_ID == 2**31 - 1
        for route in collect_api_routes(app):
            if not hasattr(route, "dependant"):
                continue
            for name, field_info in self._int_params(route):
                if not (name.endswith(self.ID_SUFFIX) or name == "offset"):
                    continue
                ceiling = self._ceiling(field_info)
                assert ceiling is not None and ceiling <= params.MAX_ID, (
                    f"{route.path}:{name} allows {ceiling}"
                )

    # ---- and what a caller actually gets ----------------------------------

    HUGE = 10**25

    @pytest.mark.parametrize(
        "url",
        [
            "/api/v1/invoices",
            "/api/v1/suppliers",
            "/api/v1/alerts",
            "/api/v1/reconciliation",
        ],
    )
    def test_an_offset_no_table_could_reach_is_refused_not_a_500(
        self, auth_client, url
    ):
        response = auth_client.get(url, params={"offset": self.HUGE})
        assert response.status_code == 422, f"{url} answered {response.status_code}"

    @pytest.mark.parametrize(
        "url",
        [
            "/api/v1/invoices/{id}",
            "/api/v1/suppliers/{id}",
            "/api/v1/reconciliation/{id}",
        ],
    )
    def test_a_row_id_wider_than_the_column_is_refused_not_a_500(
        self, auth_client, url
    ):
        response = auth_client.get(url.format(id=self.HUGE))
        assert response.status_code == 422, f"{url} answered {response.status_code}"

    @pytest.mark.parametrize(
        "method, url",
        [
            ("patch", "/api/v1/invoices/{id}"),
            ("delete", "/api/v1/invoices/{id}"),
            ("post", "/api/v1/invoices/{id}/reparse"),
            ("post", "/api/v1/alerts/{id}/read"),
            ("post", "/api/v1/alerts/{id}/dismiss"),
        ],
    )
    def test_a_write_route_refuses_it_too(self, auth_client, method, url):
        # The read routes are the ones a scanner finds. These are the ones
        # that would have taken the value all the way to a lookup.
        response = auth_client.request(method, url.format(id=self.HUGE), json={})
        assert response.status_code == 422, f"{url} answered {response.status_code}"

    @pytest.mark.parametrize(
        "url",
        [
            "/api/v1/invoices/{id}",
            "/api/v1/suppliers/{id}",
            "/api/v1/reconciliation/{id}",
        ],
    )
    def test_a_row_id_wider_than_the_column_is_refused_downwards_too(
        self, auth_client, url
    ):
        # The same width, the other way round. ``le`` alone let this through:
        # the driver then raised ``OverflowError`` — not a SQLAlchemy error, so
        # not one of the failures ``app.core.errors`` turns into a considered
        # response — and the caller got a 500 out of a URL.
        response = auth_client.get(url.format(id=-self.HUGE))
        assert response.status_code == 422, f"{url} answered {response.status_code}"

    @pytest.mark.parametrize(
        "method, url",
        [
            ("patch", "/api/v1/invoices/{id}"),
            ("delete", "/api/v1/invoices/{id}"),
            ("post", "/api/v1/invoices/{id}/reparse"),
            ("post", "/api/v1/alerts/{id}/read"),
            ("post", "/api/v1/alerts/{id}/dismiss"),
        ],
    )
    def test_a_write_route_refuses_it_downwards_too(self, auth_client, method, url):
        response = auth_client.request(method, url.format(id=-self.HUGE), json={})
        assert response.status_code == 422, f"{url} answered {response.status_code}"

    @pytest.mark.parametrize("row_id", [0, -1])
    def test_an_id_no_row_can_have_is_refused_rather_than_looked_up(
        self, auth_client, row_id
    ):
        # Narrow enough for the column and still not an id: the sequence starts
        # at 1. Refusing costs nothing and says what is wrong with the request,
        # where a 404 would say the row is merely absent.
        response = auth_client.get(f"/api/v1/invoices/{row_id}")
        assert response.status_code == 422

    def test_the_smallest_id_a_row_could_have_is_still_a_lookup(self, auth_client):
        # The guard against over-correcting: 1 is an id that can exist, so the
        # honest answer is "no such row" rather than a refusal.
        response = auth_client.get(f"/api/v1/invoices/{params.MIN_ID}")
        assert response.status_code == 404

    def test_the_largest_id_a_row_could_have_is_still_a_lookup(self, auth_client):
        # The guard against over-correcting into refusing legal ids: this is
        # an id that could exist, so the honest answer is "no such row".
        response = auth_client.get(f"/api/v1/invoices/{params.MAX_ID}")
        assert response.status_code == 404

    def test_an_offset_past_the_end_still_pages_rather_than_refusing(
        self, auth_client
    ):
        response = auth_client.get("/api/v1/invoices", params={"offset": params.MAX_ID})
        assert response.status_code == 200
        assert response.json()["items"] == []

    def test_ordinary_paging_is_unaffected(self, auth_client):
        _upload(auth_client, "TAX INVOICE INV-1 Grand Total 1180.00")
        assert auth_client.get(
            "/api/v1/invoices", params={"offset": 0, "limit": 10}
        ).status_code == 200
