"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-08-01 08:30:44.804255

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('trade_name', sa.String(length=255), nullable=True),
    sa.Column('state_code', sa.String(length=2), nullable=False),
    sa.Column('pan', sa.String(length=10), nullable=True),
    sa.Column('plan', sa.Enum('FREE', 'STARTER', 'PRO', 'CA_BUNDLE', name='businessplan', native_enum=False, length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_businesses_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_businesses_gstin'), ['gstin'], unique=True)
        batch_op.create_index(batch_op.f('ix_businesses_pan'), ['pan'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.Enum('FILING_DEADLINE', 'MISMATCH', 'ITC_AT_RISK', 'SUPPLIER_RISK', 'PLAN_LIMIT', 'PARSE_FAILED', name='alerttype', native_enum=False, length=30), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='alertseverity', native_enum=False, length=10), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'READ', 'DISMISSED', 'FAILED', name='alertstatus', native_enum=False, length=10), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('context', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index('ix_alerts_business_created', ['business_id', 'created_at'], unique=False)
        batch_op.create_index('ix_alerts_business_due', ['business_id', 'due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_business_id'), ['business_id'], unique=False)
        batch_op.create_index('ix_alerts_business_status', ['business_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_deleted_at'), ['deleted_at'], unique=False)

    op.create_table('gstr_returns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('return_type', sa.Enum('GSTR1', 'GSTR2B', 'GSTR3B', name='returntype', native_enum=False, length=10), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'READY', 'FILED', 'IMPORTED', name='returnstatus', native_enum=False, length=10), nullable=False),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('invoice_count', sa.Integer(), nullable=False),
    sa.Column('total_taxable_value', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('total_cgst', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('total_sgst', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('total_igst', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('total_cess', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arn', sa.String(length=32), nullable=True),
    sa.Column('validation_errors', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'period', 'return_type', name='uq_gstr_returns_business_period_type')
    )
    with op.batch_alter_table('gstr_returns', schema=None) as batch_op:
        batch_op.create_index('ix_gstr_returns_business_created', ['business_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_gstr_returns_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gstr_returns_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_gstr_returns_period'), ['period'], unique=False)

    op.create_table('reconciliation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', name='reconciliationstatus', native_enum=False, length=20), nullable=False),
    sa.Column('total_invoices', sa.Integer(), nullable=False),
    sa.Column('matched_count', sa.Integer(), nullable=False),
    sa.Column('mismatched_count', sa.Integer(), nullable=False),
    sa.Column('missing_in_2b_count', sa.Integer(), nullable=False),
    sa.Column('missing_in_books_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('itc_eligible', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('itc_at_risk', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('itc_claimed', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('report', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reconciliation_runs', schema=None) as batch_op:
        batch_op.create_index('ix_reconciliation_runs_business_created', ['business_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconciliation_runs_business_id'), ['business_id'], unique=False)
        batch_op.create_index('ix_reconciliation_runs_business_period', ['business_id', 'period'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconciliation_runs_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconciliation_runs_period'), ['period'], unique=False)

    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('trade_name', sa.String(length=255), nullable=True),
    sa.Column('state_code', sa.String(length=2), nullable=True),
    sa.Column('compliance_score', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'UNKNOWN', name='risklevel', native_enum=False, length=10), nullable=False),
    sa.Column('total_invoices', sa.Integer(), nullable=False),
    sa.Column('matched_invoices', sa.Integer(), nullable=False),
    sa.Column('mismatched_invoices', sa.Integer(), nullable=False),
    sa.Column('missing_invoices', sa.Integer(), nullable=False),
    sa.Column('late_filings', sa.Integer(), nullable=False),
    sa.Column('last_filed_period', sa.String(length=7), nullable=True),
    sa.Column('last_seen_at', sa.Date(), nullable=True),
    sa.Column('filing_history', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'gstin', name='uq_suppliers_business_gstin')
    )
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_index('ix_suppliers_business_created', ['business_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_suppliers_business_id'), ['business_id'], unique=False)
        batch_op.create_index('ix_suppliers_business_risk', ['business_id', 'risk_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_suppliers_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_suppliers_gstin'), ['gstin'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('OWNER', 'ACCOUNTANT', 'VIEWER', name='userrole', native_enum=False, length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('invoice_type', sa.Enum('SALES', 'PURCHASE', name='invoicetype', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'PROCESSING', 'PARSED', 'FAILED', 'MATCHED', 'MISMATCHED', 'MISSING_IN_2B', name='invoicestatus', native_enum=False, length=20), nullable=False),
    sa.Column('source', sa.Enum('UPLOAD', 'EMAIL', 'WHATSAPP', 'GSTR2B_IMPORT', 'MANUAL', name='invoicesource', native_enum=False, length=20), nullable=False),
    sa.Column('counterparty_gstin', sa.String(length=15), nullable=True),
    sa.Column('counterparty_name', sa.String(length=255), nullable=True),
    sa.Column('invoice_number', sa.String(length=64), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('period', sa.String(length=7), nullable=True),
    sa.Column('place_of_supply', sa.String(length=2), nullable=True),
    sa.Column('hsn_code', sa.String(length=8), nullable=True),
    sa.Column('taxable_value', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('cgst', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('sgst', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('igst', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('cess', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('itc_eligible', sa.Boolean(), nullable=False),
    sa.Column('reverse_charge', sa.Boolean(), nullable=False),
    sa.Column('line_items', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('source_filename', sa.String(length=255), nullable=True),
    sa.Column('storage_path', sa.String(length=512), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('extraction', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('parsed_with', sa.String(length=100), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('parse_error', sa.Text(), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'invoice_type', 'counterparty_gstin', 'invoice_number', name='uq_invoices_business_type_party_number')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index('ix_invoices_business_created', ['business_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_business_id'), ['business_id'], unique=False)
        batch_op.create_index('ix_invoices_business_period', ['business_id', 'period'], unique=False)
        batch_op.create_index('ix_invoices_business_status', ['business_id', 'status'], unique=False)
        batch_op.create_index('ix_invoices_business_type_date', ['business_id', 'invoice_type', 'invoice_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_counterparty_gstin'), ['counterparty_gstin'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_file_hash'), ['file_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_hsn_code'), ['hsn_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_invoice_number'), ['invoice_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_supplier_id'), ['supplier_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_invoice_number'))
        batch_op.drop_index(batch_op.f('ix_invoices_hsn_code'))
        batch_op.drop_index(batch_op.f('ix_invoices_file_hash'))
        batch_op.drop_index(batch_op.f('ix_invoices_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_invoices_counterparty_gstin'))
        batch_op.drop_index('ix_invoices_business_type_date')
        batch_op.drop_index('ix_invoices_business_status')
        batch_op.drop_index('ix_invoices_business_period')
        batch_op.drop_index(batch_op.f('ix_invoices_business_id'))
        batch_op.drop_index('ix_invoices_business_created')

    op.drop_table('invoices')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_business_id'))

    op.drop_table('users')
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppliers_gstin'))
        batch_op.drop_index(batch_op.f('ix_suppliers_deleted_at'))
        batch_op.drop_index('ix_suppliers_business_risk')
        batch_op.drop_index(batch_op.f('ix_suppliers_business_id'))
        batch_op.drop_index('ix_suppliers_business_created')

    op.drop_table('suppliers')
    with op.batch_alter_table('reconciliation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reconciliation_runs_period'))
        batch_op.drop_index(batch_op.f('ix_reconciliation_runs_deleted_at'))
        batch_op.drop_index('ix_reconciliation_runs_business_period')
        batch_op.drop_index(batch_op.f('ix_reconciliation_runs_business_id'))
        batch_op.drop_index('ix_reconciliation_runs_business_created')

    op.drop_table('reconciliation_runs')
    with op.batch_alter_table('gstr_returns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gstr_returns_period'))
        batch_op.drop_index(batch_op.f('ix_gstr_returns_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_gstr_returns_business_id'))
        batch_op.drop_index('ix_gstr_returns_business_created')

    op.drop_table('gstr_returns')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_deleted_at'))
        batch_op.drop_index('ix_alerts_business_status')
        batch_op.drop_index(batch_op.f('ix_alerts_business_id'))
        batch_op.drop_index('ix_alerts_business_due')
        batch_op.drop_index('ix_alerts_business_created')

    op.drop_table('alerts')
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_businesses_pan'))
        batch_op.drop_index(batch_op.f('ix_businesses_gstin'))
        batch_op.drop_index(batch_op.f('ix_businesses_deleted_at'))

    op.drop_table('businesses')
    # ### end Alembic commands ###
