import { useEffect } from "react";
import { Link } from "react-router-dom";
import { usePageTitle } from "../../hooks/usePageTitle";
import SeoHead from "../../components/SeoHead";

export default function EInvoiceGuide() {
  usePageTitle("E-Invoice Under GST: Applicability, Format, and Process");

  useEffect(() => {
    const meta = document.querySelector('meta[name="description"]');
    if (meta) meta.content = "Complete guide to e-invoicing under GST in India. Applicability thresholds, IRN generation, e-invoice schema, IRP portals, penalties, and step-by-step process.";

    let script = document.getElementById("blog-ld-json");
    if (!script) {
      script = document.createElement("script");
      script.id = "blog-ld-json";
      script.type = "application/ld+json";
      document.head.appendChild(script);
    }
    script.textContent = JSON.stringify([
      {
        "@context": "https://schema.org",
        "@type": "Article",
        headline: "E-Invoice Under GST: Applicability, Format, and Process",
        description: "Complete guide to e-invoicing under GST — applicability thresholds, IRN generation, format, and step-by-step process.",
        url: "https://gst.doaide.com/blog/e-invoice-under-gst-guide",
        datePublished: "2026-10-07",
        dateModified: "2026-10-07",
        publisher: { "@type": "Organization", name: "DoAide" },
      },
      {
        "@context": "https://schema.org",
        "@type": "FAQPage",
        mainEntity: [
          { "@type": "Question", name: "What is the turnover threshold for e-invoicing in 2026?", acceptedAnswer: { "@type": "Answer", text: "Mandatory for businesses with aggregate turnover exceeding ₹5 crore in any FY from 2017-18 onwards. Threshold was progressively lowered from ₹500 crore." } },
          { "@type": "Question", name: "What is an IRN in e-invoicing?", acceptedAnswer: { "@type": "Answer", text: "IRN (Invoice Reference Number) is a unique 64-character hash generated by the IRP for each e-invoice. It serves as the unique identity of the invoice across the GST system and cannot be duplicated." } },
          { "@type": "Question", name: "Can e-invoices be cancelled?", acceptedAnswer: { "@type": "Answer", text: "Yes, e-invoices can be cancelled on the IRP within 24 hours of generation. After 24 hours, you must issue a credit note against the original invoice instead of cancelling it." } },
          { "@type": "Question", name: "Is e-invoicing applicable to B2C transactions?", acceptedAnswer: { "@type": "Answer", text: "No. E-invoicing is currently mandatory only for B2B, B2G (business to government), export, and SEZ supply invoices. B2C invoices, delivery challans, and bill of supply are excluded." } },
          { "@type": "Question", name: "What is the penalty for not generating e-invoices?", acceptedAnswer: { "@type": "Answer", text: "Non-generation attracts a penalty of 100% of tax due or ₹10,000 per invoice (whichever is higher). The buyer also loses ITC on invoices without valid IRN. Repeated violations may lead to suspension." } },
        ],
      },
    ]);
    return () => { script?.remove(); };
  }, []);

  return (
    <article className="blog-article">
      <SeoHead title="E-Invoice Under GST: Applicability, Format & Generation Process" description="E-invoicing guide for Indian businesses — turnover thresholds, IRN generation on IRP, JSON schema format, mandatory fields, and non-compliance penalties." path="/blog/e-invoice-under-gst-guide" />
      <h1>E-Invoice Under GST: Applicability, Format, and Process</h1>
      <p className="blog-meta">Updated October 2026 · 11 min read</p>

      <section>
        <h2>What Is E-Invoicing Under GST?</h2>
        <p>
          E-invoicing (electronic invoicing) under GST is a system where B2B invoices are
          electronically authenticated by the GST system through the Invoice Registration
          Portal (IRP). It is not about generating invoices on a government portal — businesses
          continue using their own billing software. The invoice data is reported to the IRP,
          which validates it, assigns a unique Invoice Reference Number (IRN), digitally signs
          the invoice, and returns it with a QR code.
        </p>
        <p>
          The e-invoice system was introduced to standardize invoice formats across businesses,
          reduce data entry errors, enable real-time tracking of invoices, and curb tax evasion
          through automated reconciliation. Validate your GSTIN before generating e-invoices
          using our <Link to="/gstin-validator">GSTIN Validator</Link>.
        </p>
      </section>

      <section>
        <h2>E-Invoice Applicability: Who Needs to Generate?</h2>
        <p>
          E-invoicing has been rolled out in phases based on aggregate turnover thresholds.
          The threshold is based on turnover in any financial year from 2017-18 onwards:
        </p>
        <table>
          <thead>
            <tr>
              <th>Phase</th>
              <th>Effective Date</th>
              <th>Turnover Threshold</th>
            </tr>
          </thead>
          <tbody>
            <tr><td>Phase 1</td><td>1st October 2020</td><td>&gt;₹500 crore</td></tr>
            <tr><td>Phase 2</td><td>1st January 2021</td><td>&gt;₹100 crore</td></tr>
            <tr><td>Phase 3</td><td>1st April 2021</td><td>&gt;₹50 crore</td></tr>
            <tr><td>Phase 4</td><td>1st April 2022</td><td>&gt;₹20 crore</td></tr>
            <tr><td>Phase 5</td><td>1st October 2022</td><td>&gt;₹10 crore</td></tr>
            <tr><td>Phase 6</td><td>1st August 2023</td><td>&gt;₹5 crore</td></tr>
          </tbody>
        </table>
        <p>
          <strong>Exempted categories:</strong> SEZ units (not SEZ developers), insurers, banking
          and financial institutions, NBFCs, GTA, passenger transport services, cinema ticket
          booking, and suppliers of electricity.
        </p>
      </section>

      <section>
        <h2>Documents Covered Under E-Invoicing</h2>
        <ul>
          <li><strong>Covered:</strong> B2B invoices, B2G invoices, export invoices, SEZ supply invoices, credit notes, and debit notes</li>
          <li><strong>Not covered:</strong> B2C invoices, bill of supply, delivery challans, job work challans, ISD invoices, and self-invoices for reverse charge</li>
        </ul>
      </section>

      <section>
        <h2>E-Invoice Schema and Format</h2>
        <p>
          The e-invoice schema follows the standard notified by GSTN. It contains approximately
          140 fields organized into mandatory, conditional, and optional categories. The key
          sections of the e-invoice JSON schema include:
        </p>
        <h3>Mandatory Fields</h3>
        <ul>
          <li><strong>Transaction Details:</strong> Supply type (B2B, export, SEZ), document type (invoice, credit note, debit note)</li>
          <li><strong>Document Details:</strong> Invoice number, date, and value</li>
          <li><strong>Seller Details:</strong> GSTIN, legal name, address, state code, PIN code</li>
          <li><strong>Buyer Details:</strong> GSTIN, legal name, address, state code, PIN code (POS for inter-state)</li>
          <li><strong>Item Details:</strong> HSN code, quantity, unit, taxable value, GST rate, tax amounts</li>
          <li><strong>Value Details:</strong> Total assessable value, CGST, SGST/UTGST, IGST, cess, total invoice value</li>
        </ul>
        <p>
          Find the correct HSN codes for your items using our{" "}
          <Link to="/hsn-sac-finder">HSN/SAC Finder</Link> tool.
        </p>

        <h3>Conditional Fields</h3>
        <ul>
          <li><strong>Dispatch Details:</strong> Required when dispatch address differs from seller address</li>
          <li><strong>Ship-to Details:</strong> Required when delivery address differs from buyer address</li>
          <li><strong>Export Details:</strong> Shipping bill number, port code, currency for export invoices</li>
          <li><strong>E-way Bill:</strong> Transport details if e-way bill is to be generated simultaneously</li>
        </ul>
      </section>

      <section>
        <h2>Step-by-Step E-Invoice Generation Process</h2>
        <ol>
          <li>
            <strong>Prepare the invoice in your billing software</strong> — Generate the invoice
            with all mandatory fields as per the e-invoice schema. Your ERP or billing system
            should produce the JSON in the prescribed format.
          </li>
          <li>
            <strong>Register on the IRP</strong> — Register your GSTIN on the Invoice Registration
            Portal (einvoice1.gst.gov.in). You can register on multiple IRPs for redundancy.
            Currently, NIC (einvoice1.gst.gov.in) is the primary IRP.
          </li>
          <li>
            <strong>Generate API credentials</strong> — Create API credentials (client ID and
            secret) on the IRP. These are required for machine-to-machine invoice reporting.
          </li>
          <li>
            <strong>Push invoice data to IRP via API</strong> — Send the invoice JSON to the
            IRP&apos;s API endpoint. The IRP validates the schema, checks for duplicates, and
            verifies the GSTIN details.
          </li>
          <li>
            <strong>Receive IRN and signed invoice</strong> — On successful validation, the
            IRP returns the IRN (a 64-character hash), a digitally signed QR code, and the
            signed invoice JSON. The IRN is also pushed to the GST portal automatically.
          </li>
          <li>
            <strong>Print the invoice with QR code</strong> — Include the QR code on the
            printed invoice. The QR code contains key invoice details that can be verified by
            the buyer or tax authorities.
          </li>
          <li>
            <strong>Auto-population in GSTR-1</strong> — E-invoice data is automatically
            populated in your GSTR-1. You do not need to enter these invoices again while filing
            your return.
          </li>
        </ol>
      </section>

      <section>
        <h2>Understanding IRN (Invoice Reference Number)</h2>
        <p>
          The IRN is a unique 64-character hash generated using the supplier&apos;s GSTIN,
          document type, document number, and financial year. Key points:
        </p>
        <ul>
          <li>Each invoice gets a unique IRN — duplicate invoice numbers for the same GSTIN and financial year are rejected</li>
          <li>The IRN is valid for the lifetime of the invoice and cannot be reused</li>
          <li>IRN generation is real-time — the IRP responds within seconds</li>
          <li>Without a valid IRN, the invoice is not considered a valid tax invoice under GST</li>
          <li>The IRN is also used for e-way bill generation when both are required</li>
        </ul>
      </section>

      <section>
        <h2>E-Invoice and E-Way Bill Integration</h2>
        <p>
          E-invoicing and e-way bills are integrated. When generating an e-invoice, you can
          include transport details in the same request, and an e-way bill (Part A) is
          generated simultaneously. This eliminates the need to separately generate e-way bills
          on the e-way bill portal for the same transaction.
        </p>
        <p>
          Check our <Link to="/eway-bill">E-Way Bill</Link> tool for more details on e-way bill
          requirements and thresholds.
        </p>
      </section>

      <section>
        <h2>Common E-Invoice Errors and Solutions</h2>
        <table>
          <thead>
            <tr>
              <th>Error</th>
              <th>Cause</th>
              <th>Solution</th>
            </tr>
          </thead>
          <tbody>
            <tr><td>Duplicate IRN</td><td>Same invoice number for same GSTIN and FY</td><td>Use unique invoice numbers; check existing IRNs before retrying</td></tr>
            <tr><td>Invalid GSTIN</td><td>Buyer/seller GSTIN is inactive or incorrect</td><td>Verify GSTIN status on the GST portal before invoicing</td></tr>
            <tr><td>HSN code mismatch</td><td>HSN code not valid for the supply type</td><td>Use 4/6/8-digit HSN codes as per turnover slab requirements</td></tr>
            <tr><td>Schema validation failed</td><td>Missing mandatory fields or wrong data types</td><td>Validate JSON against the schema before submitting to IRP</td></tr>
            <tr><td>Authentication failure</td><td>Expired or invalid API credentials</td><td>Regenerate API credentials on the IRP portal</td></tr>
            <tr><td>Timeout</td><td>IRP server load during peak hours</td><td>Retry with exponential backoff; use alternate IRP</td></tr>
          </tbody>
        </table>
      </section>

      <section>
        <h2>Cancellation and Amendment of E-Invoices</h2>
        <h3>Cancellation (Within 24 Hours)</h3>
        <p>
          An e-invoice can be cancelled on the IRP within 24 hours of generation. After
          cancellation, the IRN becomes invalid, and the invoice data is removed from GSTR-1
          auto-population. The same invoice number cannot be reused after cancellation.
        </p>
        <h3>After 24 Hours</h3>
        <p>
          If you need to cancel an invoice after 24 hours, you cannot cancel it on the IRP.
          Instead, issue a credit note against the original invoice. The credit note must also
          be reported to the IRP and will get its own IRN.
        </p>
      </section>

      <section>
        <h2>Penalties for Non-Compliance</h2>
        <ul>
          <li><strong>Not generating e-invoice:</strong> Penalty of 100% of the tax due or ₹10,000 per invoice, whichever is higher</li>
          <li><strong>Incorrect e-invoice:</strong> Treated as incorrect invoice — buyer loses ITC eligibility</li>
          <li><strong>Repeated non-compliance:</strong> May result in suspension of GST registration</li>
          <li><strong>E-way bill impact:</strong> If e-invoicing is mandatory but not done, e-way bills generated for those goods may also be invalid</li>
        </ul>
      </section>

      <section>
        <h2>Best Practices for E-Invoicing</h2>
        <ul>
          <li>Validate invoice JSON against the schema before pushing to IRP — reduces rejection rates</li>
          <li>Maintain a mapping of HSN codes for all your products and services</li>
          <li>Use the <Link to="/calculator">GST Calculator</Link> to verify tax calculations before invoice generation</li>
          <li>Set up automated retry logic for IRP API failures with exponential backoff</li>
          <li>Register on multiple IRPs (NIC, ClearTax IRP, Cygnet IRP) for redundancy</li>
          <li>Archive all IRN responses and signed invoices for audit purposes</li>
          <li>Reconcile e-invoice data with GSTR-1 auto-populated entries before filing</li>
          <li>Train your accounting team on e-invoice cancellation timelines (24-hour window)</li>
        </ul>
      </section>

      <section>
        <h2>How DoAide GST Simplifies E-Invoicing</h2>
        <p>
          DoAide GST integrates with the IRP to validate and generate e-invoices directly from
          your invoicing workflow. Auto-populate HSN codes, validate GSTIN details in real-time,
          and track IRN status for all your invoices — all from one dashboard.
        </p>
        <p>
          <Link to="/">Try DoAide GST free →</Link>
        </p>
      </section>

      <section>
        <h2>Frequently Asked Questions</h2>

        <h3>What is the turnover threshold for e-invoicing in 2026?</h3>
        <p>
          As of 2026, e-invoicing is mandatory for businesses with aggregate turnover exceeding
          ₹5 crore in any financial year from 2017-18 onwards. The government has been
          progressively lowering the threshold — from ₹500 crore when the system launched in
          October 2020 to ₹5 crore as of August 2023. Further reductions may be announced.
        </p>

        <h3>What is an IRN in e-invoicing?</h3>
        <p>
          IRN stands for Invoice Reference Number. It is a unique 64-character hash generated
          by the IRP using the supplier GSTIN, document type, document number, and financial year.
          The IRN serves as a unique identity for each invoice in the entire GST ecosystem.
        </p>

        <h3>Can e-invoices be cancelled?</h3>
        <p>
          Yes, but only within 24 hours of generation on the IRP portal. After 24 hours,
          cancellation is not possible — you must issue a credit note against the original
          invoice instead.
        </p>

        <h3>Is e-invoicing applicable to B2C transactions?</h3>
        <p>
          No. Currently, e-invoicing is mandatory only for B2B supplies, exports, supplies to
          SEZ (with/without payment), and deemed exports. B2C invoices, bill of supply, delivery
          challans, and job work challans are excluded from e-invoicing requirements.
        </p>

        <h3>What is the penalty for not generating e-invoices?</h3>
        <p>
          Non-generation of e-invoices when mandatory attracts a penalty of 100% of the tax
          due on that invoice or ₹10,000, whichever is higher. Additionally, the buyer loses
          the right to claim ITC on invoices that do not have a valid IRN.
        </p>
      </section>
    </article>
  );
}
