const HSN_DATA = [
  { code: "0101", desc: "Live horses, asses, mules and hinnies", rate: 0, category: "Live Animals" },
  { code: "0102", desc: "Live bovine animals", rate: 0, category: "Live Animals" },
  { code: "0105", desc: "Live poultry (fowls, ducks, geese, turkeys)", rate: 0, category: "Live Animals" },
  { code: "0106", desc: "Other live animals", rate: 0, category: "Live Animals" },
  { code: "0201", desc: "Meat of bovine animals, fresh or chilled", rate: 0, category: "Food" },
  { code: "0202", desc: "Frozen bovine meat", rate: 0, category: "Meat" },
  { code: "0203", desc: "Fresh, chilled or frozen pork", rate: 0, category: "Meat" },
  { code: "0204", desc: "Fresh, chilled or frozen meat of sheep or goats", rate: 0, category: "Meat" },
  { code: "0207", desc: "Fresh, chilled or frozen poultry meat and offal", rate: 0, category: "Meat" },
  { code: "0208", desc: "Other fresh, chilled or frozen meat (rabbit, venison)", rate: 0, category: "Meat" },
  { code: "0210", desc: "Dried, salted or smoked meat and edible offal", rate: 5, category: "Meat" },
  { code: "0301", desc: "Live fish", rate: 0, category: "Fish" },
  { code: "0302", desc: "Fresh or chilled fish (excluding fillets)", rate: 0, category: "Fish" },
  { code: "0303", desc: "Frozen fish (excluding fillets)", rate: 0, category: "Fish" },
  { code: "0304", desc: "Fish fillets and other fish meat (fresh, chilled, frozen)", rate: 0, category: "Fish" },
  { code: "0305", desc: "Dried, salted or smoked fish; fish meal", rate: 5, category: "Fish" },
  { code: "0306", desc: "Crustaceans (shrimps, crabs, lobsters) fresh or frozen", rate: 0, category: "Fish" },
  { code: "0307", desc: "Molluscs (oysters, mussels, squid, octopus) fresh or frozen", rate: 0, category: "Fish" },
  { code: "0401", desc: "Milk and cream, not concentrated", rate: 0, category: "Food" },
  { code: "0402", desc: "Milk and cream, concentrated or sweetened", rate: 5, category: "Food" },
  { code: "0403", desc: "Buttermilk, curd, yogurt and kephir", rate: 0, category: "Dairy" },
  { code: "0404", desc: "Whey and modified whey products", rate: 5, category: "Dairy" },
  { code: "0405", desc: "Butter and ghee", rate: 5, category: "Dairy" },
  { code: "0406", desc: "Cheese and curd", rate: 5, category: "Food" },
  { code: "0407", desc: "Birds' eggs in shell, fresh", rate: 0, category: "Dairy" },
  { code: "0408", desc: "Egg yolks (dried, cooked, preserved)", rate: 5, category: "Dairy" },
  { code: "0409", desc: "Natural honey", rate: 0, category: "Dairy" },
  { code: "0410", desc: "Edible products of animal origin not elsewhere specified", rate: 5, category: "Dairy" },
  { code: "0504", desc: "Guts, bladders and stomachs of animals", rate: 0, category: "Animal Products" },
  { code: "0505", desc: "Skins and feathers of birds; down", rate: 5, category: "Animal Products" },
  { code: "0511", desc: "Animal semen; animal products not elsewhere specified", rate: 0, category: "Animal Products" },
  { code: "0601", desc: "Bulbs, tubers, corms, crowns and rhizomes", rate: 0, category: "Plants" },
  { code: "0602", desc: "Live plants, cuttings and slips; mushroom spawn", rate: 0, category: "Plants" },
  { code: "0603", desc: "Cut flowers and flower buds for bouquets, fresh or dried", rate: 5, category: "Plants" },
  { code: "0604", desc: "Foliage, branches without flowers", rate: 0, category: "Plants" },
  { code: "0701", desc: "Potatoes, fresh or chilled", rate: 0, category: "Food" },
  { code: "0702", desc: "Tomatoes, fresh or chilled", rate: 0, category: "Food" },
  { code: "0703", desc: "Onions, shallots, garlic and leeks, fresh or chilled", rate: 0, category: "Vegetables" },
  { code: "0704", desc: "Cabbages, cauliflowers, broccoli, fresh or chilled", rate: 0, category: "Vegetables" },
  { code: "0706", desc: "Carrots, turnips, beetroot, radishes, fresh or chilled", rate: 0, category: "Vegetables" },
  { code: "0707", desc: "Cucumbers and gherkins, fresh or chilled", rate: 0, category: "Vegetables" },
  { code: "0708", desc: "Leguminous vegetables (peas, beans) fresh or chilled", rate: 0, category: "Vegetables" },
  { code: "0709", desc: "Other fresh vegetables (mushrooms, capsicum, spinach)", rate: 0, category: "Vegetables" },
  { code: "0710", desc: "Frozen vegetables (uncooked or cooked by steaming)", rate: 5, category: "Vegetables" },
  { code: "0712", desc: "Dried vegetables, whole, cut, sliced or in powder", rate: 0, category: "Vegetables" },
  { code: "0713", desc: "Dried leguminous vegetables (dal, lentils)", rate: 0, category: "Food" },
  { code: "0801", desc: "Coconuts, brazil nuts and cashew nuts, fresh or dried", rate: 0, category: "Fruits" },
  { code: "0802", desc: "Almonds, hazelnuts, walnuts, pistachios and other nuts", rate: 0, category: "Fruits" },
  { code: "0803", desc: "Bananas and plantains, fresh or dried", rate: 0, category: "Fruits" },
  { code: "0804", desc: "Dates, figs, pineapples, avocados, mangoes, fresh", rate: 0, category: "Fruits" },
  { code: "0805", desc: "Citrus fruit (oranges, lemons, limes, grapefruit)", rate: 0, category: "Fruits" },
  { code: "0806", desc: "Grapes, fresh or dried (raisins)", rate: 0, category: "Fruits" },
  { code: "0807", desc: "Melons and papayas, fresh", rate: 0, category: "Fruits" },
  { code: "0808", desc: "Apples, pears and quinces, fresh", rate: 0, category: "Fruits" },
  { code: "0809", desc: "Apricots, cherries, peaches, plums and sloes, fresh", rate: 0, category: "Fruits" },
  { code: "0810", desc: "Strawberries, raspberries, kiwifruit and other fresh fruits", rate: 0, category: "Fruits" },
  { code: "0811", desc: "Frozen fruits and nuts (uncooked or steamed)", rate: 5, category: "Fruits" },
  { code: "0813", desc: "Dried fruits (apricots, prunes, raisins, mixed)", rate: 0, category: "Fruits" },
  { code: "0901", desc: "Coffee, whether or not roasted", rate: 5, category: "Food" },
  { code: "0902", desc: "Tea, whether or not flavoured", rate: 5, category: "Food" },
  { code: "0903", desc: "Mate", rate: 5, category: "Spices" },
  { code: "0904", desc: "Pepper (black, white, long) and capsicum dried", rate: 5, category: "Spices" },
  { code: "0905", desc: "Vanilla beans", rate: 5, category: "Spices" },
  { code: "0906", desc: "Cinnamon and cinnamon-tree bark", rate: 5, category: "Spices" },
  { code: "0907", desc: "Cloves (whole fruit, cloves and stems)", rate: 5, category: "Spices" },
  { code: "0908", desc: "Nutmeg, mace and cardamoms", rate: 5, category: "Spices" },
  { code: "0909", desc: "Seeds of anise, cumin, coriander, fennel", rate: 5, category: "Spices" },
  { code: "0910", desc: "Ginger, turmeric, saffron, thyme, bay leaves, curry powder", rate: 5, category: "Spices" },
  { code: "1001", desc: "Wheat and meslin", rate: 0, category: "Food" },
  { code: "1002", desc: "Rye", rate: 0, category: "Cereals" },
  { code: "1003", desc: "Barley", rate: 0, category: "Cereals" },
  { code: "1004", desc: "Oats", rate: 0, category: "Cereals" },
  { code: "1005", desc: "Maize (corn)", rate: 0, category: "Food" },
  { code: "1006", desc: "Rice", rate: 5, category: "Food" },
  { code: "1007", desc: "Grain sorghum (jowar)", rate: 0, category: "Cereals" },
  { code: "1008", desc: "Millets, buckwheat, quinoa and other cereals", rate: 0, category: "Cereals" },
  { code: "1101", desc: "Wheat or meslin flour (atta)", rate: 0, category: "Food" },
  { code: "1102", desc: "Cereal flours (other than wheat or meslin)", rate: 0, category: "Milling" },
  { code: "1103", desc: "Cereal groats, meal, pellets; semolina (suji/rava)", rate: 0, category: "Milling" },
  { code: "1104", desc: "Rolled, flaked or milled cereal grains (oatmeal, poha)", rate: 5, category: "Milling" },
  { code: "1105", desc: "Flour, meal, powder and flakes of potato", rate: 0, category: "Milling" },
  { code: "1106", desc: "Flour and meal of dried leguminous vegetables (besan)", rate: 0, category: "Milling" },
  { code: "1107", desc: "Malt, whether or not roasted", rate: 18, category: "Milling" },
  { code: "1108", desc: "Starches; inulin", rate: 18, category: "Milling" },
  { code: "1201", desc: "Soybeans, whether or not broken", rate: 0, category: "Oil Seeds" },
  { code: "1202", desc: "Groundnuts (peanuts), not roasted", rate: 0, category: "Oil Seeds" },
  { code: "1205", desc: "Rape or colza seeds (mustard seeds)", rate: 0, category: "Oil Seeds" },
  { code: "1206", desc: "Sunflower seeds, whether or not broken", rate: 0, category: "Oil Seeds" },
  { code: "1207", desc: "Other oil seeds (sesame, safflower, linseed)", rate: 0, category: "Oil Seeds" },
  { code: "1209", desc: "Seeds, fruits and spores for sowing", rate: 0, category: "Oil Seeds" },
  { code: "1210", desc: "Hop cones, fresh or dried; lupulin", rate: 5, category: "Oil Seeds" },
  { code: "1211", desc: "Medicinal plants (tulsi, neem, ashwagandha, aloe vera)", rate: 0, category: "Oil Seeds" },
  { code: "1212", desc: "Seaweed, sugar beet, sugar cane", rate: 0, category: "Oil Seeds" },
  { code: "1301", desc: "Lac, shellac and similar natural gums and resins", rate: 5, category: "Gums & Resins" },
  { code: "1302", desc: "Vegetable saps and extracts (henna, aloe)", rate: 5, category: "Gums & Resins" },
  { code: "1401", desc: "Bamboo, rattan, reeds and similar materials", rate: 0, category: "Vegetable Plaiting" },
  { code: "1404", desc: "Other vegetable products not elsewhere specified", rate: 0, category: "Vegetable Plaiting" },
  { code: "1501", desc: "Animal fats and oils", rate: 18, category: "Food" },
  { code: "1502", desc: "Rendered fats of bovine animals, sheep or goats (tallow)", rate: 5, category: "Fats & Oils" },
  { code: "1504", desc: "Fish oils and fats (cod liver oil)", rate: 5, category: "Fats & Oils" },
  { code: "1507", desc: "Soya-bean oil", rate: 5, category: "Food" },
  { code: "1508", desc: "Groundnut (peanut) oil and its fractions", rate: 5, category: "Fats & Oils" },
  { code: "1509", desc: "Olive oil, virgin", rate: 5, category: "Fats & Oils" },
  { code: "1510", desc: "Other olive oils and blends", rate: 5, category: "Fats & Oils" },
  { code: "1511", desc: "Palm oil", rate: 5, category: "Food" },
  { code: "1512", desc: "Sunflower oil, safflower oil", rate: 5, category: "Food" },
  { code: "1513", desc: "Coconut oil (copra oil) and its fractions", rate: 5, category: "Fats & Oils" },
  { code: "1514", desc: "Rapeseed (canola) or mustard oil", rate: 5, category: "Fats & Oils" },
  { code: "1515", desc: "Groundnut oil, olive oil, other fixed vegetable oils", rate: 5, category: "Food" },
  { code: "1516", desc: "Hydrogenated animal or vegetable fats (vanaspati)", rate: 5, category: "Fats & Oils" },
  { code: "1517", desc: "Margarine and edible preparations of fats", rate: 5, category: "Fats & Oils" },
  { code: "1518", desc: "Animal or vegetable fats, boiled, oxidised or modified", rate: 18, category: "Fats & Oils" },
  { code: "1520", desc: "Glycerol, crude; glycerol waters and lyes", rate: 18, category: "Fats & Oils" },
  { code: "1521", desc: "Vegetable waxes, beeswax and other insect waxes", rate: 18, category: "Fats & Oils" },
  { code: "1601", desc: "Sausages and similar products of meat or offal", rate: 18, category: "Prepared Foods" },
  { code: "1602", desc: "Prepared or preserved meat (corned beef, luncheon meat)", rate: 18, category: "Prepared Foods" },
  { code: "1604", desc: "Prepared or preserved fish; caviar", rate: 18, category: "Prepared Foods" },
  { code: "1605", desc: "Prepared or preserved crustaceans and molluscs", rate: 18, category: "Prepared Foods" },
  { code: "1701", desc: "Cane or beet sugar", rate: 5, category: "Food" },
  { code: "1702", desc: "Other sugars (glucose, fructose, maltose)", rate: 18, category: "Sugar & Confectionery" },
  { code: "1703", desc: "Molasses from sugar extraction or refining", rate: 18, category: "Sugar & Confectionery" },
  { code: "1704", desc: "Sugar confectionery (not containing cocoa)", rate: 18, category: "Food" },
  { code: "1801", desc: "Cocoa beans, whole or broken, raw or roasted", rate: 5, category: "Cocoa" },
  { code: "1803", desc: "Cocoa paste, whether or not defatted", rate: 18, category: "Cocoa" },
  { code: "1804", desc: "Cocoa butter, fat and oil", rate: 18, category: "Cocoa" },
  { code: "1805", desc: "Cocoa powder, not containing added sugar", rate: 18, category: "Cocoa" },
  { code: "1806", desc: "Chocolate and other food preparations containing cocoa", rate: 18, category: "Food" },
  { code: "1901", desc: "Malt extract; food preparations of flour", rate: 18, category: "Food" },
  { code: "1902", desc: "Pasta, noodles, couscous and vermicelli", rate: 18, category: "Cereal Preparations" },
  { code: "1903", desc: "Tapioca and substitutes from starch (sago)", rate: 0, category: "Cereal Preparations" },
  { code: "1904", desc: "Prepared cereal-based foods (cornflakes, muesli, puffed rice)", rate: 18, category: "Cereal Preparations" },
  { code: "1905", desc: "Bread, biscuits, cakes, pastry", rate: 18, category: "Food" },
  { code: "2001", desc: "Pickles; vegetables/fruits preserved in vinegar", rate: 18, category: "Prepared Foods" },
  { code: "2002", desc: "Tomatoes prepared or preserved (tomato paste)", rate: 18, category: "Prepared Foods" },
  { code: "2003", desc: "Mushrooms and truffles prepared or preserved", rate: 18, category: "Prepared Foods" },
  { code: "2004", desc: "Frozen prepared or preserved vegetables", rate: 18, category: "Prepared Foods" },
  { code: "2005", desc: "Other prepared vegetables (potato chips, canned)", rate: 18, category: "Prepared Foods" },
  { code: "2006", desc: "Vegetables, fruits, nuts preserved by sugar", rate: 18, category: "Prepared Foods" },
  { code: "2007", desc: "Jams, fruit jellies, marmalades and fruit pastes", rate: 18, category: "Prepared Foods" },
  { code: "2008", desc: "Prepared nuts, peanut butter, fruits prepared", rate: 18, category: "Prepared Foods" },
  { code: "2009", desc: "Fruit juices and vegetable juices, unfermented", rate: 18, category: "Beverages" },
  { code: "2101", desc: "Coffee and tea extracts, essences and concentrates", rate: 18, category: "Prepared Foods" },
  { code: "2102", desc: "Yeast (active or inactive); baking powders", rate: 18, category: "Prepared Foods" },
  { code: "2103", desc: "Sauces, ketchup, mustard, mixed condiments", rate: 18, category: "Prepared Foods" },
  { code: "2104", desc: "Soups and broths, preparations thereof", rate: 18, category: "Prepared Foods" },
  { code: "2105", desc: "Ice cream and other edible ice", rate: 18, category: "Prepared Foods" },
  { code: "2106", desc: "Food preparations not elsewhere specified (namkeen, papad)", rate: 18, category: "Food" },
  { code: "2201", desc: "Waters, including mineral and aerated waters", rate: 18, category: "Beverages" },
  { code: "2202", desc: "Sweetened or flavoured water, soft drinks", rate: 40, category: "Beverages" },
  { code: "2203", desc: "Beer made from malt", rate: 0, category: "Beverages" },
  { code: "2204", desc: "Wine of fresh grapes", rate: 0, category: "Beverages" },
  { code: "2207", desc: "Undenatured ethyl alcohol; denatured spirits", rate: 18, category: "Beverages" },
  { code: "2209", desc: "Vinegar and substitutes from acetic acid", rate: 18, category: "Beverages" },
  { code: "2301", desc: "Flour, meals of meat/fish for animal feed", rate: 0, category: "Animal Feed" },
  { code: "2302", desc: "Bran, sharps and other residues of cereals", rate: 0, category: "Animal Feed" },
  { code: "2304", desc: "Oil-cake and residues of soybean oil extraction", rate: 0, category: "Animal Feed" },
  { code: "2306", desc: "Oil-cake and residues of other vegetable fats", rate: 0, category: "Animal Feed" },
  { code: "2309", desc: "Preparations for animal feeding (cattle/poultry feed)", rate: 0, category: "Animal Feed" },
  { code: "2401", desc: "Unmanufactured tobacco; tobacco refuse", rate: 40, category: "Tobacco" },
  { code: "2402", desc: "Cigars, cigarettes, tobacco", rate: 40, category: "Tobacco" },
  { code: "2403", desc: "Other manufactured tobacco (gutka, pan masala with tobacco)", rate: 40, category: "Tobacco" },
  { code: "2501", desc: "Common salt, sea salt, rock salt", rate: 0, category: "Minerals" },
  { code: "2505", desc: "Natural sands (silica, quartz, industrial sands)", rate: 5, category: "Minerals" },
  { code: "2506", desc: "Quartz and quartzite", rate: 5, category: "Minerals" },
  { code: "2510", desc: "Natural calcium phosphates and phosphatic chalk", rate: 5, category: "Minerals" },
  { code: "2515", desc: "Marble, travertine and calcareous stone", rate: 18, category: "Minerals" },
  { code: "2516", desc: "Granite, sandstone and building stone", rate: 18, category: "Minerals" },
  { code: "2517", desc: "Pebbles, gravel, broken or crushed stone; macadam", rate: 5, category: "Minerals" },
  { code: "2521", desc: "Limestone for cement manufacture", rate: 5, category: "Minerals" },
  { code: "2523", desc: "Portland cement, aluminous cement", rate: 18, category: "Construction" },
  { code: "2601", desc: "Iron ores and concentrates", rate: 5, category: "Ores" },
  { code: "2602", desc: "Manganese ores and concentrates", rate: 5, category: "Ores" },
  { code: "2603", desc: "Copper ores and concentrates", rate: 5, category: "Ores" },
  { code: "2606", desc: "Aluminium ores (bauxite) and concentrates", rate: 5, category: "Ores" },
  { code: "2701", desc: "Coal; briquettes and solid fuels from coal", rate: 5, category: "Mineral Fuels" },
  { code: "2702", desc: "Lignite, whether or not agglomerated", rate: 5, category: "Mineral Fuels" },
  { code: "2704", desc: "Coke and semi-coke of coal, lignite or peat", rate: 5, category: "Mineral Fuels" },
  { code: "2706", desc: "Tar distilled from coal, lignite or peat", rate: 18, category: "Mineral Fuels" },
  { code: "2710", desc: "Petroleum oils (petrol, diesel, ATF)", rate: 18, category: "Fuel" },
  { code: "2711", desc: "Petroleum gases (LPG, natural gas)", rate: 5, category: "Fuel" },
  { code: "2713", desc: "Petroleum coke, petroleum bitumen and residues", rate: 18, category: "Mineral Fuels" },
  { code: "2801", desc: "Fluorine, chlorine, bromine and iodine", rate: 18, category: "Chemicals" },
  { code: "2803", desc: "Carbon (carbon blacks and other forms)", rate: 18, category: "Chemicals" },
  { code: "2804", desc: "Hydrogen, nitrogen, oxygen, rare gases", rate: 18, category: "Chemicals" },
  { code: "2806", desc: "Hydrochloric acid; chlorosulphuric acid", rate: 18, category: "Chemicals" },
  { code: "2807", desc: "Sulphuric acid; oleum", rate: 18, category: "Chemicals" },
  { code: "2811", desc: "Other inorganic acids and oxygen compounds", rate: 18, category: "Chemicals" },
  { code: "2814", desc: "Ammonia, anhydrous or in aqueous solution", rate: 18, category: "Chemicals" },
  { code: "2815", desc: "Sodium hydroxide (caustic soda); potassium hydroxide", rate: 18, category: "Chemicals" },
  { code: "2836", desc: "Carbonates; peroxocarbonates; sodium bicarbonate", rate: 18, category: "Chemicals" },
  { code: "2901", desc: "Acyclic hydrocarbons (ethylene, propylene)", rate: 18, category: "Chemicals" },
  { code: "2902", desc: "Cyclic hydrocarbons (benzene, toluene, xylenes)", rate: 18, category: "Chemicals" },
  { code: "2905", desc: "Acyclic alcohols (methanol, propanol, glycerol)", rate: 18, category: "Chemicals" },
  { code: "2915", desc: "Acetic acid, its salts and anhydrides", rate: 18, category: "Chemicals" },
  { code: "2933", desc: "Heterocyclic compounds with nitrogen hetero-atoms", rate: 18, category: "Chemicals" },
  { code: "2936", desc: "Provitamins and vitamins, natural or synthesised", rate: 5, category: "Chemicals" },
  { code: "2937", desc: "Hormones, prostaglandins, thromboxanes", rate: 5, category: "Chemicals" },
  { code: "2941", desc: "Antibiotics", rate: 5, category: "Chemicals" },
  { code: "3001", desc: "Dried glands and organs for organotherapeutic uses", rate: 5, category: "Pharmaceuticals" },
  { code: "3002", desc: "Human/animal blood; antisera, vaccines, toxins", rate: 5, category: "Pharmaceuticals" },
  { code: "3003", desc: "Medicaments (unmixed, not in measured doses)", rate: 5, category: "Pharmaceuticals" },
  { code: "3004", desc: "Medicaments (medicines for therapeutic use)", rate: 5, category: "Pharma" },
  { code: "3005", desc: "Bandages, dressings, medical supplies", rate: 5, category: "Pharma" },
  { code: "3006", desc: "Pharmaceutical preparations (surgical sutures, blood-grouping reagents)", rate: 5, category: "Pharma" },
  { code: "3101", desc: "Animal or vegetable fertilisers; guano", rate: 5, category: "Fertilizers" },
  { code: "3102", desc: "Mineral or chemical nitrogenous fertilisers (urea)", rate: 5, category: "Fertilizers" },
  { code: "3103", desc: "Mineral or chemical phosphatic fertilisers", rate: 5, category: "Fertilizers" },
  { code: "3104", desc: "Mineral or chemical potassic fertilisers", rate: 5, category: "Fertilizers" },
  { code: "3105", desc: "Mineral/chemical fertilisers with two or more nutrients", rate: 5, category: "Fertilizers" },
  { code: "3201", desc: "Tanning extracts of vegetable origin; tannins", rate: 18, category: "Dyes & Pigments" },
  { code: "3204", desc: "Synthetic colouring matter; dyes", rate: 18, category: "Chemicals" },
  { code: "3205", desc: "Colour lakes; preparations based on colour lakes", rate: 18, category: "Dyes & Pigments" },
  { code: "3206", desc: "Inorganic pigments (titanium dioxide, chrome colours)", rate: 18, category: "Dyes & Pigments" },
  { code: "3207", desc: "Prepared pigments and colours for ceramics", rate: 18, category: "Dyes & Pigments" },
  { code: "3208", desc: "Paints and varnishes", rate: 18, category: "Chemicals" },
  { code: "3209", desc: "Water-based paints and varnishes (emulsions)", rate: 18, category: "Paints" },
  { code: "3210", desc: "Other paints and varnishes; prepared water pigments", rate: 18, category: "Paints" },
  { code: "3213", desc: "Artists' colours", rate: 18, category: "Chemicals" },
  { code: "3214", desc: "Glaziers putty, grafting putty, resin cements", rate: 18, category: "Paints" },
  { code: "3215", desc: "Printing ink, writing or drawing ink", rate: 18, category: "Dyes & Pigments" },
  { code: "3301", desc: "Essential oils (lemon, peppermint, eucalyptus)", rate: 18, category: "Perfumery" },
  { code: "3302", desc: "Mixtures of odoriferous substances for food industry", rate: 18, category: "Perfumery" },
  { code: "3303", desc: "Perfumes and toilet waters (eau de toilette)", rate: 18, category: "Perfumery" },
  { code: "3304", desc: "Beauty or make-up preparations, skincare", rate: 18, category: "Cosmetics" },
  { code: "3305", desc: "Hair care preparations (shampoo, conditioner)", rate: 18, category: "Cosmetics" },
  { code: "3306", desc: "Oral or dental hygiene preparations (toothpaste)", rate: 18, category: "Cosmetics" },
  { code: "3307", desc: "Deodorants, bath preparations, room fresheners", rate: 18, category: "Perfumery" },
  { code: "3401", desc: "Soap, washing preparations, detergent", rate: 18, category: "Household" },
  { code: "3402", desc: "Cleaning preparations, surface-active agents", rate: 18, category: "Household" },
  { code: "3403", desc: "Lubricating preparations (cutting oil, rust preventives)", rate: 18, category: "Soap & Cleaning" },
  { code: "3405", desc: "Polishes and creams for footwear, furniture, floors", rate: 18, category: "Soap & Cleaning" },
  { code: "3406", desc: "Candles, tapers and the like", rate: 5, category: "Soap & Cleaning" },
  { code: "3501", desc: "Casein, caseinates and other casein derivatives", rate: 18, category: "Protein Substances" },
  { code: "3503", desc: "Gelatin and gelatin derivatives; isinglass", rate: 18, category: "Protein Substances" },
  { code: "3506", desc: "Prepared glues and adhesives not elsewhere specified", rate: 18, category: "Protein Substances" },
  { code: "3604", desc: "Fireworks, signalling flares, rain rockets", rate: 18, category: "Explosives" },
  { code: "3605", desc: "Matches (other than pyrotechnic articles)", rate: 5, category: "Explosives" },
  { code: "3701", desc: "Photographic plates and film, sensitised", rate: 18, category: "Photography" },
  { code: "3702", desc: "Photographic film in rolls, sensitised", rate: 18, category: "Photography" },
  { code: "3802", desc: "Activated carbon; activated natural mineral products", rate: 18, category: "Chemicals" },
  { code: "3808", desc: "Insecticides, fungicides, herbicides", rate: 18, category: "Chemicals" },
  { code: "3814", desc: "Organic composite solvents and thinners", rate: 18, category: "Chemicals" },
  { code: "3822", desc: "Diagnostic or laboratory reagents on a backing", rate: 18, category: "Chemicals" },
  { code: "3826", desc: "Biodiesel and mixtures thereof", rate: 5, category: "Chemicals" },
  { code: "3901", desc: "Polyethylene in primary forms", rate: 18, category: "Plastics" },
  { code: "3902", desc: "Polypropylene in primary forms", rate: 18, category: "Plastics" },
  { code: "3903", desc: "Polystyrene in primary forms", rate: 18, category: "Plastics" },
  { code: "3904", desc: "PVC (polyvinyl chloride) in primary forms", rate: 18, category: "Plastics" },
  { code: "3906", desc: "Acrylic polymers in primary forms", rate: 18, category: "Plastics" },
  { code: "3907", desc: "Polyacetals, polyesters in primary forms", rate: 18, category: "Plastics" },
  { code: "3909", desc: "Amino resins, phenolic resins in primary forms", rate: 18, category: "Plastics" },
  { code: "3917", desc: "Tubes, pipes and hoses of plastics", rate: 18, category: "Plastics" },
  { code: "3918", desc: "Plastic floor coverings, wall/ceiling coverings", rate: 18, category: "Plastics" },
  { code: "3919", desc: "Self-adhesive plates, sheets, film of plastics", rate: 18, category: "Plastics" },
  { code: "3920", desc: "Plastic plates, sheets, film (packaging)", rate: 18, category: "Plastics" },
  { code: "3921", desc: "Plastic plates, sheets (cellular)", rate: 18, category: "Plastics" },
  { code: "3922", desc: "Plastic baths, sinks, wash basins, toilets", rate: 18, category: "Plastics" },
  { code: "3923", desc: "Plastic containers, bottles, bags", rate: 18, category: "Plastics" },
  { code: "3924", desc: "Plastic tableware, kitchenware, household articles", rate: 18, category: "Plastics" },
  { code: "3925", desc: "Plastic builders' ware (doors, windows, shutters)", rate: 18, category: "Plastics" },
  { code: "3926", desc: "Other articles of plastics", rate: 18, category: "Plastics" },
  { code: "4001", desc: "Natural rubber in primary forms", rate: 5, category: "Rubber" },
  { code: "4002", desc: "Synthetic rubber in primary forms", rate: 18, category: "Rubber" },
  { code: "4008", desc: "Vulcanised rubber plates, sheets, strips", rate: 18, category: "Rubber" },
  { code: "4009", desc: "Rubber tubes, pipes and hoses", rate: 18, category: "Rubber" },
  { code: "4010", desc: "Conveyor/transmission belts of vulcanised rubber", rate: 18, category: "Rubber" },
  { code: "4011", desc: "New pneumatic tyres of rubber", rate: 18, category: "Rubber" },
  { code: "4012", desc: "Retreaded or used pneumatic tyres of rubber", rate: 18, category: "Rubber" },
  { code: "4013", desc: "Inner tubes of rubber", rate: 18, category: "Rubber" },
  { code: "4014", desc: "Rubber hygienic/pharmaceutical articles, teats", rate: 18, category: "Rubber" },
  { code: "4015", desc: "Rubber garments, gloves, mittens", rate: 18, category: "Rubber" },
  { code: "4016", desc: "Other articles of vulcanised rubber (erasers, gaskets)", rate: 18, category: "Rubber" },
  { code: "4101", desc: "Raw hides and skins of bovine/equine animals", rate: 5, category: "Leather" },
  { code: "4104", desc: "Tanned/crust leather of bovine/equine animals", rate: 5, category: "Leather" },
  { code: "4107", desc: "Leather of other animals, tanned or crust", rate: 5, category: "Leather" },
  { code: "4201", desc: "Saddlery and harness for animals", rate: 18, category: "Leather Goods" },
  { code: "4202", desc: "Trunks, suitcases, handbags, wallets", rate: 18, category: "Leather" },
  { code: "4203", desc: "Leather garments, gloves, belts", rate: 5, category: "Leather" },
  { code: "4205", desc: "Other articles of leather or composition leather", rate: 18, category: "Leather Goods" },
  { code: "4301", desc: "Raw furskins, heads, tails, paws", rate: 5, category: "Furskins" },
  { code: "4303", desc: "Articles of apparel and accessories of furskin", rate: 18, category: "Furskins" },
  { code: "4401", desc: "Fuel wood, wood chips, sawdust", rate: 5, category: "Wood" },
  { code: "4403", desc: "Wood in the rough, treated or untreated", rate: 18, category: "Wood" },
  { code: "4407", desc: "Wood sawn or chipped lengthwise, sliced/peeled", rate: 18, category: "Wood" },
  { code: "4408", desc: "Veneer sheets, sheets for plywood", rate: 18, category: "Wood" },
  { code: "4410", desc: "Particle board and oriented strand board (OSB)", rate: 18, category: "Wood" },
  { code: "4411", desc: "Fibreboard, MDF of wood or ligneous materials", rate: 18, category: "Wood" },
  { code: "4412", desc: "Plywood, veneered panels, laminated wood", rate: 18, category: "Wood" },
  { code: "4415", desc: "Wooden packing cases, boxes, crates, pallets", rate: 18, category: "Wood" },
  { code: "4418", desc: "Builders' joinery (doors, windows, parquet)", rate: 18, category: "Wood" },
  { code: "4419", desc: "Wooden tableware and kitchenware", rate: 18, category: "Wood" },
  { code: "4421", desc: "Other articles of wood (pegs, hangers, spools)", rate: 18, category: "Wood" },
  { code: "4601", desc: "Plaits, basketwork, wickerwork products", rate: 18, category: "Straw & Plaiting" },
  { code: "4602", desc: "Basketwork, wickerwork articles, loofah", rate: 18, category: "Straw & Plaiting" },
  { code: "4801", desc: "Newsprint, in rolls or sheets", rate: 5, category: "Paper" },
  { code: "4802", desc: "Paper and paperboard, uncoated", rate: 5, category: "Paper" },
  { code: "4804", desc: "Uncoated kraft paper and paperboard", rate: 18, category: "Paper" },
  { code: "4808", desc: "Corrugated paper and paperboard", rate: 18, category: "Paper" },
  { code: "4810", desc: "Coated paper and paperboard", rate: 18, category: "Paper" },
  { code: "4811", desc: "Paper, coated, impregnated", rate: 18, category: "Paper" },
  { code: "4817", desc: "Envelopes, letter cards, postcards of paper", rate: 18, category: "Paper" },
  { code: "4818", desc: "Toilet paper, tissues, napkins of paper", rate: 18, category: "Paper" },
  { code: "4819", desc: "Cartons, boxes, bags of paper", rate: 18, category: "Paper" },
  { code: "4820", desc: "Registers, notebooks, diaries", rate: 5, category: "Paper" },
  { code: "4821", desc: "Paper labels and tags, printed or not", rate: 18, category: "Paper" },
  { code: "4901", desc: "Printed books, brochures, leaflets", rate: 0, category: "Paper" },
  { code: "4902", desc: "Newspapers, journals, periodicals", rate: 0, category: "Paper" },
  { code: "5001", desc: "Silk-worm cocoons suitable for reeling", rate: 5, category: "Silk" },
  { code: "5004", desc: "Silk yarn (not from waste), not for retail", rate: 5, category: "Silk" },
  { code: "5007", desc: "Woven fabrics of silk", rate: 5, category: "Textiles" },
  { code: "5201", desc: "Cotton, not carded or combed (raw cotton)", rate: 5, category: "Cotton" },
  { code: "5204", desc: "Cotton sewing thread, retail or not", rate: 5, category: "Cotton" },
  { code: "5205", desc: "Cotton yarn (not sewing thread), 85%+ cotton", rate: 5, category: "Cotton" },
  { code: "5208", desc: "Woven fabrics of cotton", rate: 5, category: "Textiles" },
  { code: "5209", desc: "Woven fabrics of cotton (above 200g/m2)", rate: 5, category: "Textiles" },
  { code: "5210", desc: "Woven cotton fabric with man-made fibre, denim", rate: 5, category: "Cotton" },
  { code: "5303", desc: "Jute and other textile bast fibres, raw", rate: 5, category: "Textiles" },
  { code: "5305", desc: "Coconut, abaca, sisal and other plant fibres", rate: 5, category: "Textiles" },
  { code: "5310", desc: "Woven fabrics of jute or other bast fibres", rate: 5, category: "Textiles" },
  { code: "5402", desc: "Synthetic filament yarn, not for retail sale", rate: 5, category: "Textiles" },
  { code: "5407", desc: "Woven fabrics of synthetic filament yarn", rate: 5, category: "Textiles" },
  { code: "5503", desc: "Synthetic staple fibres, not carded/combed", rate: 5, category: "Textiles" },
  { code: "5509", desc: "Yarn of synthetic staple fibres, not retail", rate: 5, category: "Textiles" },
  { code: "5512", desc: "Woven fabrics of synthetic staple fibres, 85%+", rate: 5, category: "Textiles" },
  { code: "5513", desc: "Woven fabrics of synthetic staple fibres", rate: 5, category: "Textiles" },
  { code: "5601", desc: "Wadding of textile materials and articles", rate: 5, category: "Textiles" },
  { code: "5603", desc: "Nonwovens, whether or not impregnated/coated", rate: 5, category: "Textiles" },
  { code: "5607", desc: "Twine, cordage, ropes and cables", rate: 5, category: "Textiles" },
  { code: "5608", desc: "Knotted netting of twine, rope (fishing nets)", rate: 5, category: "Textiles" },
  { code: "5701", desc: "Carpets, hand-knotted or hand-woven", rate: 5, category: "Textiles" },
  { code: "5702", desc: "Carpets, woven, not tufted or flocked", rate: 5, category: "Textiles" },
  { code: "5703", desc: "Carpets, tufted, whether or not made up", rate: 5, category: "Textiles" },
  { code: "5903", desc: "Textile fabrics, impregnated, coated, laminated", rate: 5, category: "Textiles" },
  { code: "6001", desc: "Pile fabrics, knitted or crocheted", rate: 5, category: "Textiles" },
  { code: "6101", desc: "Men's overcoats, jackets (knitted)", rate: 5, category: "Garments" },
  { code: "6102", desc: "Women's overcoats, cloaks, knitted", rate: 5, category: "Apparel" },
  { code: "6103", desc: "Men's suits, jackets, trousers, knitted", rate: 5, category: "Apparel" },
  { code: "6104", desc: "Women's suits, dresses, skirts (knitted)", rate: 5, category: "Garments" },
  { code: "6105", desc: "Men's shirts, knitted or crocheted", rate: 5, category: "Apparel" },
  { code: "6106", desc: "Women's blouses and shirts, knitted", rate: 5, category: "Apparel" },
  { code: "6107", desc: "Men's underpants, pyjamas, robes, knitted", rate: 5, category: "Apparel" },
  { code: "6108", desc: "Women's slips, petticoats, briefs, knitted", rate: 5, category: "Apparel" },
  { code: "6109", desc: "T-shirts, singlets, vests (knitted)", rate: 5, category: "Garments" },
  { code: "6110", desc: "Jerseys, pullovers, cardigans (knitted)", rate: 5, category: "Garments" },
  { code: "6111", desc: "Babies' garments and accessories, knitted", rate: 5, category: "Apparel" },
  { code: "6112", desc: "Track suits, ski suits, swimwear, knitted", rate: 5, category: "Apparel" },
  { code: "6114", desc: "Other garments, knitted or crocheted", rate: 5, category: "Apparel" },
  { code: "6115", desc: "Hosiery, stockings, socks, knitted", rate: 5, category: "Apparel" },
  { code: "6116", desc: "Gloves, mittens, mitts, knitted", rate: 5, category: "Apparel" },
  { code: "6201", desc: "Men's overcoats, cloaks, wind-jackets", rate: 5, category: "Apparel" },
  { code: "6202", desc: "Women's overcoats, cloaks, wind-jackets", rate: 5, category: "Apparel" },
  { code: "6203", desc: "Men's suits, trousers, shorts", rate: 5, category: "Garments" },
  { code: "6204", desc: "Women's suits, trousers, shorts", rate: 5, category: "Garments" },
  { code: "6205", desc: "Men's shirts", rate: 5, category: "Garments" },
  { code: "6206", desc: "Women's blouses, shirts", rate: 5, category: "Garments" },
  { code: "6207", desc: "Men's singlets, undershirts, pyjamas", rate: 5, category: "Apparel" },
  { code: "6208", desc: "Women's singlets, slips, petticoats", rate: 5, category: "Apparel" },
  { code: "6209", desc: "Babies' garments and accessories, not knitted", rate: 5, category: "Apparel" },
  { code: "6211", desc: "Track suits, ski suits, swimwear, not knitted", rate: 5, category: "Apparel" },
  { code: "6212", desc: "Brassieres, girdles, corsets, suspenders", rate: 5, category: "Apparel" },
  { code: "6213", desc: "Handkerchiefs of textile materials", rate: 5, category: "Apparel" },
  { code: "6214", desc: "Shawls, scarves, mufflers, veils", rate: 5, category: "Apparel" },
  { code: "6215", desc: "Ties, bow ties, cravats", rate: 5, category: "Apparel" },
  { code: "6301", desc: "Blankets and travelling rugs", rate: 5, category: "Textiles" },
  { code: "6302", desc: "Bed linen, table linen, toilet/kitchen linen", rate: 5, category: "Textiles" },
  { code: "6303", desc: "Curtains, drapes, interior blinds of textile", rate: 5, category: "Textiles" },
  { code: "6304", desc: "Furnishing articles (bedspreads, cushions)", rate: 5, category: "Textiles" },
  { code: "6305", desc: "Sacks and bags for packing of textile", rate: 5, category: "Textiles" },
  { code: "6306", desc: "Tarpaulins, tents, sails, camping goods", rate: 5, category: "Textiles" },
  { code: "6307", desc: "Floor cloths, dish cloths, dusters, life jackets", rate: 5, category: "Textiles" },
  { code: "6401", desc: "Waterproof footwear", rate: 18, category: "Footwear" },
  { code: "6402", desc: "Footwear with outer soles of rubber or plastics", rate: 18, category: "Footwear" },
  { code: "6403", desc: "Footwear with leather uppers", rate: 18, category: "Footwear" },
  { code: "6404", desc: "Footwear with textile uppers, rubber/plastic soles", rate: 5, category: "Footwear" },
  { code: "6405", desc: "Other footwear (wooden, cork uppers)", rate: 5, category: "Footwear" },
  { code: "6406", desc: "Parts of footwear (uppers, soles, heels)", rate: 18, category: "Footwear" },
  { code: "6505", desc: "Hats and headgear, knitted or from lace/felt", rate: 18, category: "Headgear" },
  { code: "6506", desc: "Safety headgear, helmets, hard hats", rate: 18, category: "Headgear" },
  { code: "6601", desc: "Umbrellas and sun umbrellas", rate: 18, category: "Umbrellas" },
  { code: "6602", desc: "Walking sticks, seat-sticks, whips, crops", rate: 18, category: "Umbrellas" },
  { code: "6702", desc: "Artificial flowers, foliage, fruit", rate: 18, category: "Feathers & Artificial Flowers" },
  { code: "6704", desc: "Wigs, false beards, eyebrows of human/animal hair", rate: 18, category: "Feathers & Artificial Flowers" },
  { code: "6801", desc: "Setts, curbstones, flagstones of natural stone", rate: 18, category: "Stone & Cement" },
  { code: "6802", desc: "Worked monumental stone, marble, granite", rate: 18, category: "Construction" },
  { code: "6806", desc: "Mineral wool, slag wool thermal insulation", rate: 18, category: "Stone & Cement" },
  { code: "6809", desc: "Articles of plaster or compositions of plaster", rate: 18, category: "Stone & Cement" },
  { code: "6810", desc: "Cement, concrete or artificial stone articles", rate: 18, category: "Stone & Cement" },
  { code: "6813", desc: "Friction material for brakes, clutches", rate: 18, category: "Stone & Cement" },
  { code: "6901", desc: "Bricks, blocks, tiles of siliceous earth", rate: 5, category: "Ceramics" },
  { code: "6902", desc: "Refractory bricks, blocks, tiles", rate: 18, category: "Ceramics" },
  { code: "6904", desc: "Ceramic building bricks, flooring blocks", rate: 5, category: "Ceramics" },
  { code: "6905", desc: "Roofing tiles, chimney pots of ceramics", rate: 5, category: "Ceramics" },
  { code: "6906", desc: "Ceramic pipes, conduits, guttering", rate: 18, category: "Ceramics" },
  { code: "6907", desc: "Ceramic tiles for floors and walls", rate: 18, category: "Construction" },
  { code: "6910", desc: "Ceramic sinks, wash basins, baths, toilets", rate: 18, category: "Construction" },
  { code: "6911", desc: "Tableware, kitchenware of porcelain", rate: 5, category: "Household" },
  { code: "6912", desc: "Ceramic tableware, kitchenware (non-porcelain)", rate: 18, category: "Ceramics" },
  { code: "6913", desc: "Ceramic statuettes and ornamental articles", rate: 18, category: "Ceramics" },
  { code: "7005", desc: "Float glass, polished glass in sheets", rate: 18, category: "Construction" },
  { code: "7007", desc: "Safety glass (toughened/tempered, laminated)", rate: 18, category: "Glass" },
  { code: "7009", desc: "Glass mirrors, framed or unframed", rate: 18, category: "Glass" },
  { code: "7010", desc: "Glass carboys, bottles, jars, phials, ampoules", rate: 18, category: "Glass" },
  { code: "7013", desc: "Glassware for table, kitchen use", rate: 18, category: "Household" },
  { code: "7016", desc: "Glass paving blocks, bricks for building", rate: 18, category: "Glass" },
  { code: "7017", desc: "Laboratory, hygienic, pharmaceutical glassware", rate: 18, category: "Glass" },
  { code: "7019", desc: "Glass fibres, rovings, yarn, mats, fabrics", rate: 18, category: "Glass" },
  { code: "7101", desc: "Pearls, natural or cultured", rate: 3, category: "Precious Metals & Stones" },
  { code: "7102", desc: "Diamonds, worked or unworked", rate: 0.25, category: "Precious Metals & Stones" },
  { code: "7103", desc: "Precious stones (rubies, sapphires, emeralds)", rate: 3, category: "Precious Metals & Stones" },
  { code: "7104", desc: "Synthetic or reconstructed precious stones", rate: 3, category: "Precious Metals & Stones" },
  { code: "7106", desc: "Silver, unwrought or semi-manufactured", rate: 3, category: "Precious Metals & Stones" },
  { code: "7108", desc: "Gold, unwrought or semi-manufactured", rate: 3, category: "Precious Metals & Stones" },
  { code: "7110", desc: "Platinum, unwrought or semi-manufactured", rate: 3, category: "Precious Metals & Stones" },
  { code: "7113", desc: "Jewellery of precious metal", rate: 3, category: "Jewellery" },
  { code: "7114", desc: "Articles of goldsmiths' or silversmiths' wares", rate: 3, category: "Jewellery" },
  { code: "7115", desc: "Articles of precious metal (wire, foil, tubes)", rate: 3, category: "Precious Metals & Stones" },
  { code: "7117", desc: "Imitation jewellery", rate: 18, category: "Jewellery" },
  { code: "7118", desc: "Coin, including legal tender", rate: 3, category: "Precious Metals & Stones" },
  { code: "7201", desc: "Pig iron and spiegeleisen, ingots", rate: 18, category: "Iron & Steel" },
  { code: "7202", desc: "Ferro-alloys", rate: 18, category: "Iron & Steel" },
  { code: "7204", desc: "Ferrous waste and scrap, remelting ingots", rate: 18, category: "Iron & Steel" },
  { code: "7207", desc: "Semi-finished products of iron or non-alloy steel", rate: 18, category: "Iron & Steel" },
  { code: "7208", desc: "Flat-rolled iron/steel, hot-rolled, width >=600mm", rate: 18, category: "Iron & Steel" },
  { code: "7209", desc: "Flat-rolled iron/steel, cold-rolled, width >=600mm", rate: 18, category: "Iron & Steel" },
  { code: "7210", desc: "Hot rolled / cold rolled steel sheets", rate: 18, category: "Metals" },
  { code: "7211", desc: "Flat-rolled iron/steel, width <600mm", rate: 18, category: "Iron & Steel" },
  { code: "7212", desc: "Flat-rolled iron/steel, plated or coated", rate: 18, category: "Iron & Steel" },
  { code: "7213", desc: "Hot-rolled bars and rods of iron or steel", rate: 18, category: "Metals" },
  { code: "7214", desc: "Iron or non-alloy steel bars, rods", rate: 18, category: "Metals" },
  { code: "7215", desc: "Bars and rods of iron/steel, cold-formed", rate: 18, category: "Iron & Steel" },
  { code: "7216", desc: "Angles, shapes, sections of iron/steel", rate: 18, category: "Iron & Steel" },
  { code: "7217", desc: "Wire of iron or non-alloy steel", rate: 18, category: "Iron & Steel" },
  { code: "7219", desc: "Stainless steel flat-rolled, width >=600mm", rate: 18, category: "Iron & Steel" },
  { code: "7222", desc: "Stainless steel bars, rods, angles, shapes", rate: 18, category: "Iron & Steel" },
  { code: "7225", desc: "Flat-rolled products of alloy steel, width >=600mm", rate: 18, category: "Iron & Steel" },
  { code: "7228", desc: "Bars, rods of other alloy steel", rate: 18, category: "Iron & Steel" },
  { code: "7301", desc: "Sheet piling of iron or steel", rate: 18, category: "Iron & Steel" },
  { code: "7304", desc: "Seamless tubes and pipes of iron/steel", rate: 18, category: "Iron & Steel" },
  { code: "7305", desc: "Other tubes, pipes, welded, >406mm dia", rate: 18, category: "Iron & Steel" },
  { code: "7306", desc: "Steel tubes, pipes, hollow profiles", rate: 18, category: "Metals" },
  { code: "7307", desc: "Tube or pipe fittings of iron/steel (elbows)", rate: 18, category: "Iron & Steel" },
  { code: "7308", desc: "Structures and parts of iron or steel", rate: 18, category: "Metals" },
  { code: "7309", desc: "Reservoirs, tanks, vats of iron/steel, >300L", rate: 18, category: "Iron & Steel" },
  { code: "7310", desc: "Tanks, casks, drums, boxes of iron/steel, <=300L", rate: 18, category: "Iron & Steel" },
  { code: "7311", desc: "Containers for compressed/liquefied gas, steel", rate: 18, category: "Iron & Steel" },
  { code: "7312", desc: "Stranded wire, ropes, cables of iron/steel", rate: 18, category: "Iron & Steel" },
  { code: "7313", desc: "Barbed wire of iron/steel, fencing wire", rate: 18, category: "Iron & Steel" },
  { code: "7314", desc: "Cloth, grill, netting, fencing of iron/steel wire", rate: 18, category: "Iron & Steel" },
  { code: "7315", desc: "Chain and parts thereof of iron or steel", rate: 18, category: "Iron & Steel" },
  { code: "7317", desc: "Nails, tacks, drawing pins, staples of iron/steel", rate: 18, category: "Iron & Steel" },
  { code: "7318", desc: "Screws, bolts, nuts, washers of iron", rate: 18, category: "Metals" },
  { code: "7320", desc: "Springs and leaves for springs, of iron/steel", rate: 18, category: "Iron & Steel" },
  { code: "7321", desc: "Stoves, cookers, grills (iron or steel)", rate: 18, category: "Household" },
  { code: "7322", desc: "Radiators and parts, air heaters of iron/steel", rate: 18, category: "Iron & Steel" },
  { code: "7323", desc: "Table, kitchen articles of iron or steel", rate: 18, category: "Household" },
  { code: "7324", desc: "Sanitary ware (sinks, baths) of stainless steel", rate: 18, category: "Iron & Steel" },
  { code: "7326", desc: "Other articles of iron or steel (forgings)", rate: 18, category: "Iron & Steel" },
  { code: "7403", desc: "Refined copper, unwrought, alloys", rate: 18, category: "Copper" },
  { code: "7404", desc: "Copper waste and scrap", rate: 18, category: "Copper" },
  { code: "7407", desc: "Copper bars, rods and profiles", rate: 18, category: "Copper" },
  { code: "7408", desc: "Copper wire", rate: 18, category: "Copper" },
  { code: "7411", desc: "Copper tubes and pipes", rate: 18, category: "Copper" },
  { code: "7418", desc: "Copper table, kitchen, sanitary ware", rate: 18, category: "Copper" },
  { code: "7601", desc: "Unwrought aluminium (alloys, ingots)", rate: 18, category: "Aluminium" },
  { code: "7604", desc: "Aluminium bars, rods and profiles", rate: 18, category: "Aluminium" },
  { code: "7606", desc: "Aluminium plates, sheets, strip", rate: 18, category: "Aluminium" },
  { code: "7607", desc: "Aluminium foil, thickness <=0.2mm", rate: 18, category: "Aluminium" },
  { code: "7608", desc: "Aluminium tubes and pipes", rate: 18, category: "Aluminium" },
  { code: "7610", desc: "Aluminium structures (bridges, towers, doors)", rate: 18, category: "Aluminium" },
  { code: "7615", desc: "Aluminium table, kitchen articles", rate: 5, category: "Household" },
  { code: "7616", desc: "Other articles of aluminium", rate: 18, category: "Aluminium" },
  { code: "7801", desc: "Unwrought lead", rate: 18, category: "Other Base Metals" },
  { code: "7901", desc: "Unwrought zinc", rate: 18, category: "Other Base Metals" },
  { code: "8001", desc: "Unwrought tin", rate: 18, category: "Other Base Metals" },
  { code: "8201", desc: "Hand tools (spades, shovels, picks, hoes, forks)", rate: 18, category: "Tools & Cutlery" },
  { code: "8202", desc: "Hand saws, blades for saws of all kinds", rate: 18, category: "Tools & Cutlery" },
  { code: "8203", desc: "Files, rasps, pliers, pincers, tweezers, shears", rate: 18, category: "Tools & Cutlery" },
  { code: "8204", desc: "Hand-operated spanners and wrenches", rate: 18, category: "Tools & Cutlery" },
  { code: "8205", desc: "Other hand tools (anvils, vices, blow torches)", rate: 18, category: "Tools & Cutlery" },
  { code: "8207", desc: "Interchangeable tools for drilling, boring, milling", rate: 18, category: "Tools & Cutlery" },
  { code: "8211", desc: "Knives with cutting blades, table/pocket knives", rate: 18, category: "Tools & Cutlery" },
  { code: "8212", desc: "Razors and razor blades", rate: 18, category: "Tools & Cutlery" },
  { code: "8213", desc: "Scissors, tailors' shears, and blades", rate: 18, category: "Tools & Cutlery" },
  { code: "8215", desc: "Spoons, forks, ladles, skimmers, cake-servers", rate: 18, category: "Tools & Cutlery" },
  { code: "8301", desc: "Padlocks, locks (key/combination)", rate: 18, category: "Base Metal Articles" },
  { code: "8302", desc: "Base metal mountings, fittings (hinges, castors)", rate: 18, category: "Base Metal Articles" },
  { code: "8303", desc: "Armoured safes, strongboxes, vault doors", rate: 18, category: "Base Metal Articles" },
  { code: "8305", desc: "Staples in strips, letter clips of base metal", rate: 18, category: "Base Metal Articles" },
  { code: "8306", desc: "Bells, gongs, statuettes, trophies of base metal", rate: 18, category: "Base Metal Articles" },
  { code: "8309", desc: "Stoppers, caps, lids, seals of base metal", rate: 18, category: "Base Metal Articles" },
  { code: "8311", desc: "Wire, rods, electrodes for soldering/welding", rate: 18, category: "Base Metal Articles" },
  { code: "8402", desc: "Steam or other vapour generating boilers", rate: 18, category: "Machinery" },
  { code: "8407", desc: "Spark-ignition internal combustion engines", rate: 18, category: "Machinery" },
  { code: "8408", desc: "Compression-ignition diesel/semi-diesel engines", rate: 18, category: "Machinery" },
  { code: "8409", desc: "Parts for spark-ignition/diesel engines", rate: 18, category: "Machinery" },
  { code: "8411", desc: "Turbo-jets, turbo-propellers, gas turbines", rate: 18, category: "Machinery" },
  { code: "8413", desc: "Pumps for liquids, liquid elevators", rate: 18, category: "Machinery" },
  { code: "8414", desc: "Air pumps, vacuum pumps, compressors, fans", rate: 18, category: "Machinery" },
  { code: "8415", desc: "Air conditioning machines", rate: 18, category: "Machinery" },
  { code: "8418", desc: "Refrigerators, freezers", rate: 18, category: "Appliances" },
  { code: "8419", desc: "Machinery for heat treatment (pasteurisers, dryers)", rate: 18, category: "Machinery" },
  { code: "8421", desc: "Centrifuges, filters, water purifiers", rate: 18, category: "Machinery" },
  { code: "8422", desc: "Dish washing machines", rate: 18, category: "Appliances" },
  { code: "8423", desc: "Weighing machinery, weights for balances", rate: 18, category: "Machinery" },
  { code: "8424", desc: "Mechanical spraying apparatus, fire extinguishers", rate: 18, category: "Machinery" },
  { code: "8426", desc: "Ships' derricks, cranes, mobile lifting frames", rate: 18, category: "Machinery" },
  { code: "8427", desc: "Fork-lift trucks, works trucks with lifting gear", rate: 18, category: "Machinery" },
  { code: "8429", desc: "Self-propelled bulldozers, excavators, graders", rate: 18, category: "Machinery" },
  { code: "8432", desc: "Agricultural machinery (ploughs, harrows, seeders)", rate: 18, category: "Machinery" },
  { code: "8433", desc: "Harvesting, threshing machinery, mowers", rate: 18, category: "Machinery" },
  { code: "8436", desc: "Other agricultural/horticultural/poultry machinery", rate: 18, category: "Machinery" },
  { code: "8437", desc: "Machines for cleaning, sorting seed/grain, milling", rate: 18, category: "Machinery" },
  { code: "8438", desc: "Food/drink industry machinery, sugar manufacture", rate: 18, category: "Machinery" },
  { code: "8443", desc: "Printing machinery; printers, copiers", rate: 18, category: "Machinery" },
  { code: "8446", desc: "Weaving machines, looms", rate: 18, category: "Machinery" },
  { code: "8450", desc: "Washing machines", rate: 18, category: "Appliances" },
  { code: "8452", desc: "Sewing machines", rate: 18, category: "Machinery" },
  { code: "8462", desc: "Machine tools for forging, stamping, pressing metal", rate: 18, category: "Machinery" },
  { code: "8465", desc: "Machine tools for working wood, cork, bone", rate: 18, category: "Machinery" },
  { code: "8467", desc: "Pneumatic hand tools (rotary, percussive)", rate: 18, category: "Machinery" },
  { code: "8471", desc: "Computers and data processing machines", rate: 18, category: "Electronics" },
  { code: "8473", desc: "Parts and accessories for computers", rate: 18, category: "Electronics" },
  { code: "8474", desc: "Machinery for sorting, screening, crushing, mixing", rate: 18, category: "Machinery" },
  { code: "8477", desc: "Machinery for working rubber or plastics", rate: 18, category: "Machinery" },
  { code: "8479", desc: "Machines with individual functions (presses, mixers)", rate: 18, category: "Machinery" },
  { code: "8481", desc: "Taps, cocks, valves for pipes, tanks, boilers", rate: 18, category: "Machinery" },
  { code: "8482", desc: "Ball or roller bearings", rate: 18, category: "Machinery" },
  { code: "8483", desc: "Transmission shafts, cranks, bearing housings, gears", rate: 18, category: "Machinery" },
  { code: "8501", desc: "Electric motors and generators", rate: 18, category: "Electronics" },
  { code: "8502", desc: "Electric generating sets and rotary converters", rate: 18, category: "Electrical" },
  { code: "8503", desc: "Parts for electric motors, generators", rate: 18, category: "Electrical" },
  { code: "8504", desc: "Electrical transformers, static converters, UPS", rate: 18, category: "Electronics" },
  { code: "8505", desc: "Electro-magnets, electromagnetic chucks, brakes", rate: 18, category: "Electrical" },
  { code: "8506", desc: "Primary cells and batteries", rate: 18, category: "Electronics" },
  { code: "8507", desc: "Electric accumulators (lithium-ion batteries)", rate: 18, category: "Electronics" },
  { code: "8508", desc: "Vacuum cleaners, including dry and wet types", rate: 18, category: "Electrical" },
  { code: "8509", desc: "Electromechanical domestic appliances (mixers, grinders)", rate: 18, category: "Electrical" },
  { code: "8510", desc: "Electric shavers, hair clippers, hair removers", rate: 18, category: "Electrical" },
  { code: "8511", desc: "Electrical ignition/starting equipment for engines", rate: 18, category: "Electrical" },
  { code: "8512", desc: "Electrical lighting/signalling for vehicles, wipers", rate: 18, category: "Electrical" },
  { code: "8513", desc: "Portable electric lamps (torches, lanterns)", rate: 18, category: "Electrical" },
  { code: "8515", desc: "Electric brazing/soldering/welding machines", rate: 18, category: "Electrical" },
  { code: "8516", desc: "Electric water heaters, hair dryers, irons", rate: 18, category: "Appliances" },
  { code: "8517", desc: "Telephone sets including smartphones", rate: 18, category: "Electronics" },
  { code: "8518", desc: "Microphones, speakers, headphones", rate: 18, category: "Electronics" },
  { code: "8519", desc: "Sound recording or reproducing apparatus", rate: 18, category: "Electrical" },
  { code: "8521", desc: "Video recording or reproducing apparatus", rate: 18, category: "Electronics" },
  { code: "8523", desc: "Discs, tapes, solid-state storage devices (pen drives, memory cards)", rate: 18, category: "Electronics" },
  { code: "8525", desc: "Transmission apparatus; cameras, camcorders", rate: 18, category: "Electronics" },
  { code: "8526", desc: "Radar apparatus, radio navigational aid apparatus", rate: 18, category: "Electrical" },
  { code: "8527", desc: "Radio broadcast receivers", rate: 18, category: "Electrical" },
  { code: "8528", desc: "Monitors and projectors; televisions", rate: 18, category: "Electronics" },
  { code: "8529", desc: "Parts for television, radio receivers/transmitters", rate: 18, category: "Electrical" },
  { code: "8531", desc: "Electric sound or visual signalling apparatus", rate: 18, category: "Electrical" },
  { code: "8532", desc: "Electrical capacitors, fixed, variable, adjustable", rate: 18, category: "Electrical" },
  { code: "8534", desc: "Printed circuits (PCBs)", rate: 18, category: "Electronics" },
  { code: "8535", desc: "Electrical apparatus for switching, >1000V", rate: 18, category: "Electrical" },
  { code: "8536", desc: "Electrical switches, fuses, connectors", rate: 18, category: "Electronics" },
  { code: "8537", desc: "Boards, panels, consoles for electric control", rate: 18, category: "Electrical" },
  { code: "8539", desc: "Electric filament or LED lamps", rate: 5, category: "Electronics" },
  { code: "8541", desc: "Semiconductor devices; LEDs; solar cells", rate: 18, category: "Electronics" },
  { code: "8542", desc: "Electronic integrated circuits and microassemblies", rate: 18, category: "Electrical" },
  { code: "8544", desc: "Insulated wire, cable; optical fibre cables", rate: 18, category: "Electronics" },
  { code: "8601", desc: "Rail locomotives powered by electric current", rate: 18, category: "Railway" },
  { code: "8603", desc: "Self-propelled railway/tramway coaches", rate: 18, category: "Railway" },
  { code: "8605", desc: "Railway passenger coaches, luggage/mail vans", rate: 5, category: "Railway" },
  { code: "8606", desc: "Railway freight wagons (tank, hopper, flat)", rate: 5, category: "Railway" },
  { code: "8607", desc: "Parts of railway locomotives or rolling stock", rate: 18, category: "Railway" },
  { code: "8608", desc: "Railway track fixtures (rails, sleepers, points)", rate: 18, category: "Railway" },
  { code: "8609", desc: "Containers designed for transport by multiple modes", rate: 18, category: "Railway" },
  { code: "8701", desc: "Tractors (agricultural, road, industrial)", rate: 5, category: "Vehicles" },
  { code: "8702", desc: "Motor vehicles for 10+ persons, buses", rate: 18, category: "Vehicles" },
  { code: "8703", desc: "Motor cars and vehicles (petrol/diesel/electric)", rate: 18, category: "Automobiles" },
  { code: "8704", desc: "Motor vehicles for transport of goods (trucks)", rate: 18, category: "Vehicles" },
  { code: "8706", desc: "Chassis fitted with engines for motor vehicles", rate: 18, category: "Vehicles" },
  { code: "8707", desc: "Bodies including cabs for motor vehicles", rate: 18, category: "Vehicles" },
  { code: "8708", desc: "Parts and accessories of motor vehicles", rate: 18, category: "Vehicles" },
  { code: "8711", desc: "Motorcycles and cycles with auxiliary motor", rate: 18, category: "Automobiles" },
  { code: "8712", desc: "Bicycles and other cycles (not motorized)", rate: 5, category: "Automobiles" },
  { code: "8713", desc: "Wheelchairs, whether or not motorised", rate: 0, category: "Vehicles" },
  { code: "8714", desc: "Parts and accessories for motorcycles and bicycles", rate: 18, category: "Automobiles" },
  { code: "8716", desc: "Trailers, semi-trailers, non-mechanical vehicles", rate: 18, category: "Vehicles" },
  { code: "8801", desc: "Balloons, dirigibles, gliders, hang gliders, kites", rate: 5, category: "Aircraft" },
  { code: "8802", desc: "Aeroplanes, helicopters, spacecraft, satellites", rate: 5, category: "Aircraft" },
  { code: "8803", desc: "Parts of balloons, aircraft, helicopters, spacecraft", rate: 18, category: "Aircraft" },
  { code: "8804", desc: "Parachutes and rotochutes, parts and accessories", rate: 18, category: "Aircraft" },
  { code: "8901", desc: "Cruise ships, cargo vessels, barges", rate: 5, category: "Ships" },
  { code: "8902", desc: "Fishing vessels, factory ships", rate: 5, category: "Ships" },
  { code: "8903", desc: "Yachts and other pleasure or sports boats", rate: 40, category: "Ships" },
  { code: "8904", desc: "Tugs and pusher craft", rate: 5, category: "Ships" },
  { code: "8905", desc: "Light-vessels, dredgers, floating docks/cranes", rate: 5, category: "Ships" },
  { code: "8907", desc: "Floating structures (rafts, pontoons, buoys)", rate: 18, category: "Ships" },
  { code: "9001", desc: "Optical fibres and cables; lenses", rate: 18, category: "Optical" },
  { code: "9002", desc: "Lenses, prisms, mirrors, optical elements mounted", rate: 18, category: "Instruments" },
  { code: "9003", desc: "Frames and mountings for spectacles/goggles", rate: 18, category: "Instruments" },
  { code: "9004", desc: "Spectacles, goggles, sunglasses", rate: 18, category: "Optical" },
  { code: "9005", desc: "Binoculars, monoculars, telescopes", rate: 18, category: "Instruments" },
  { code: "9006", desc: "Photographic cameras, flash apparatus", rate: 18, category: "Instruments" },
  { code: "9011", desc: "Compound optical microscopes", rate: 18, category: "Instruments" },
  { code: "9015", desc: "Surveying, hydrographic, meteorological instruments", rate: 18, category: "Instruments" },
  { code: "9017", desc: "Drawing, marking-out, mathematical instruments", rate: 18, category: "Instruments" },
  { code: "9018", desc: "Medical, surgical or dental instruments", rate: 5, category: "Medical" },
  { code: "9021", desc: "Orthopaedic appliances, hearing aids", rate: 5, category: "Medical" },
  { code: "9022", desc: "Apparatus based on X-rays, alpha, beta, gamma rays", rate: 18, category: "Instruments" },
  { code: "9025", desc: "Hydrometers, thermometers, pyrometers", rate: 18, category: "Instruments" },
  { code: "9026", desc: "Instruments for measuring flow, level, pressure", rate: 18, category: "Instruments" },
  { code: "9027", desc: "Instruments for physical/chemical analysis (spectrometers)", rate: 18, category: "Instruments" },
  { code: "9028", desc: "Gas, liquid, electricity supply meters", rate: 18, category: "Instruments" },
  { code: "9030", desc: "Oscilloscopes, spectrum analysers, multimeters", rate: 18, category: "Instruments" },
  { code: "9031", desc: "Measuring or checking instruments (projectors)", rate: 18, category: "Instruments" },
  { code: "9032", desc: "Automatic regulating or controlling instruments", rate: 18, category: "Instruments" },
  { code: "9101", desc: "Wrist-watches with case of precious metal", rate: 18, category: "Clocks & Watches" },
  { code: "9102", desc: "Wrist-watches, other than precious metal case", rate: 18, category: "Clocks & Watches" },
  { code: "9103", desc: "Clocks with watch movements", rate: 18, category: "Clocks & Watches" },
  { code: "9105", desc: "Other clocks (wall, mantel, cuckoo, alarm)", rate: 18, category: "Clocks & Watches" },
  { code: "9111", desc: "Watch cases and parts of watch cases", rate: 18, category: "Clocks & Watches" },
  { code: "9113", desc: "Watch straps, bands and bracelets", rate: 18, category: "Clocks & Watches" },
  { code: "9201", desc: "Pianos, including automatic, harpsichords", rate: 18, category: "Musical Instruments" },
  { code: "9202", desc: "String instruments (guitars, violins, harps)", rate: 18, category: "Musical Instruments" },
  { code: "9205", desc: "Wind instruments (clarinets, trumpets, flutes)", rate: 18, category: "Musical Instruments" },
  { code: "9206", desc: "Percussion instruments (drums, xylophones, cymbals)", rate: 18, category: "Musical Instruments" },
  { code: "9207", desc: "Musical instruments, sound produced electrically", rate: 18, category: "Musical Instruments" },
  { code: "9209", desc: "Parts and accessories of musical instruments", rate: 18, category: "Musical Instruments" },
  { code: "9301", desc: "Military weapons, other than revolvers/pistols", rate: 18, category: "Arms & Ammunition" },
  { code: "9303", desc: "Other firearms (shotguns, rifles)", rate: 18, category: "Arms & Ammunition" },
  { code: "9304", desc: "Air guns, spring guns, truncheons", rate: 18, category: "Arms & Ammunition" },
  { code: "9306", desc: "Bombs, grenades, ammunition, cartridges, pellets", rate: 18, category: "Arms & Ammunition" },
  { code: "9401", desc: "Seats and parts (chairs, sofas)", rate: 18, category: "Furniture" },
  { code: "9402", desc: "Medical, surgical, dental, veterinary furniture", rate: 18, category: "Furniture" },
  { code: "9403", desc: "Other furniture (tables, desks, wardrobes)", rate: 18, category: "Furniture" },
  { code: "9404", desc: "Mattress supports; mattresses", rate: 18, category: "Furniture" },
  { code: "9405", desc: "Lamps and lighting fittings", rate: 18, category: "Furniture" },
  { code: "9406", desc: "Prefabricated buildings", rate: 18, category: "Furniture" },
  { code: "9503", desc: "Toys, games; tricycles, dolls", rate: 5, category: "Toys" },
  { code: "9504", desc: "Video game consoles, carrom boards, chess", rate: 18, category: "Toys" },
  { code: "9505", desc: "Festive, carnival, entertainment articles", rate: 18, category: "Toys & Games" },
  { code: "9506", desc: "Sports equipment, gym articles", rate: 5, category: "Sports" },
  { code: "9507", desc: "Fishing rods, tackle, landing nets", rate: 18, category: "Toys & Games" },
  { code: "9601", desc: "Worked ivory, bone, horn, coral, shell", rate: 18, category: "Miscellaneous" },
  { code: "9603", desc: "Brooms, brushes, squeegees, mops, feather dusters", rate: 18, category: "Miscellaneous" },
  { code: "9606", desc: "Buttons, press-fasteners, snap-fasteners", rate: 18, category: "Miscellaneous" },
  { code: "9607", desc: "Slide fasteners, zippers, and parts thereof", rate: 18, category: "Miscellaneous" },
  { code: "9608", desc: "Ball point pens, felt tipped pens", rate: 18, category: "Stationery" },
  { code: "9609", desc: "Pencils, crayons, chalk", rate: 5, category: "Stationery" },
  { code: "9611", desc: "Date, sealing, numbering stamps", rate: 18, category: "Miscellaneous" },
  { code: "9613", desc: "Cigarette lighters and other lighters", rate: 18, category: "Miscellaneous" },
  { code: "9615", desc: "Combs, hair-slides, hairpins, curling pins", rate: 18, category: "Miscellaneous" },
  { code: "9617", desc: "Vacuum flasks, thermos, parts", rate: 18, category: "Miscellaneous" },
  { code: "9619", desc: "Sanitary towels, napkins, diapers", rate: 5, category: "Health" },
  { code: "9954", desc: "Construction services", rate: 18, category: "Services", sac: true },
  { code: "9961", desc: "Financial and insurance services", rate: 18, category: "Services", sac: true },
  { code: "9962", desc: "Financial and related services (banking, lending)", rate: 18, category: "Services", sac: true },
  { code: "9963", desc: "Leasing or rental services", rate: 18, category: "Services", sac: true },
  { code: "9964", desc: "Passenger transport services", rate: 5, category: "Services", sac: true },
  { code: "9965", desc: "Goods transport services", rate: 5, category: "Services", sac: true },
  { code: "9966", desc: "Rental services of transport vehicles", rate: 18, category: "Services", sac: true },
  { code: "9967", desc: "Cargo handling, warehousing and storage services", rate: 18, category: "Services", sac: true },
  { code: "9968", desc: "Postal and courier services", rate: 18, category: "Services", sac: true },
  { code: "9969", desc: "Electricity, gas and water distribution services", rate: 18, category: "Services", sac: true },
  { code: "9970", desc: "Environmental protection services", rate: 18, category: "Services", sac: true },
  { code: "9971", desc: "Financial intermediation and related services", rate: 18, category: "Services", sac: true },
  { code: "9972", desc: "Real estate services", rate: 18, category: "Services", sac: true },
  { code: "9973", desc: "Leasing / rental without operator", rate: 18, category: "Services", sac: true },
  { code: "9974", desc: "Accommodation, food and beverage services", rate: 18, category: "Services", sac: true },
  { code: "9975", desc: "Public healthcare and residential care services", rate: 0, category: "Services", sac: true },
  { code: "9976", desc: "Government social security and welfare services", rate: 0, category: "Services", sac: true },
  { code: "9977", desc: "Community, social and personal services", rate: 18, category: "Services", sac: true },
  { code: "9978", desc: "Printing, publishing and reproduction services", rate: 18, category: "Services", sac: true },
  { code: "9979", desc: "Entertainment, amusement and recreation services", rate: 18, category: "Services", sac: true },
  { code: "9980", desc: "Domestic services (cooks, drivers, maids)", rate: 18, category: "Services", sac: true },
  { code: "9981", desc: "Research and development services", rate: 18, category: "Services", sac: true },
  { code: "9982", desc: "Legal and accounting services", rate: 18, category: "Services", sac: true },
  { code: "9983", desc: "Other professional, technical, business services (IT, consulting)", rate: 18, category: "Services", sac: true },
  { code: "9984", desc: "Telecommunications, broadcasting services", rate: 18, category: "Services", sac: true },
  { code: "9985", desc: "Support services (security, cleaning, temp staffing)", rate: 18, category: "Services", sac: true },
  { code: "9986", desc: "Support services to agriculture, forestry", rate: 0, category: "Services", sac: true },
  { code: "9987", desc: "Maintenance and repair services", rate: 18, category: "Services", sac: true },
  { code: "9988", desc: "Manufacturing services on physical inputs", rate: 18, category: "Services", sac: true },
  { code: "9989", desc: "Other manufacturing services, sub-contracting", rate: 18, category: "Services", sac: true },
  { code: "9990", desc: "Services of charitable/religious organisations", rate: 0, category: "Services", sac: true },
  { code: "9991", desc: "Public administration services", rate: 0, category: "Services", sac: true },
  { code: "9992", desc: "Education services", rate: 0, category: "Services", sac: true },
  { code: "9993", desc: "Health and social care services", rate: 0, category: "Services", sac: true },
  { code: "9994", desc: "Sewage and waste collection, treatment, disposal", rate: 18, category: "Services", sac: true },
  { code: "9995", desc: "Services of membership organisations", rate: 18, category: "Services", sac: true },
  { code: "9996", desc: "Recreational, cultural and sporting services", rate: 18, category: "Services", sac: true },
  { code: "9997", desc: "Other services (laundry, beauty, wellness, funeral)", rate: 18, category: "Services", sac: true },
  { code: "9998", desc: "Employment services, manpower supply", rate: 18, category: "Services", sac: true },
];

const _lowerCache = new Map();

function lowerFields(item) {
  if (_lowerCache.has(item)) return _lowerCache.get(item);
  const entry = {
    code: item.code,
    desc: item.desc.toLowerCase(),
    category: item.category.toLowerCase(),
  };
  _lowerCache.set(item, entry);
  return entry;
}

export function searchHSN(query, { limit = 20 } = {}) {
  const q = (query || "").trim().toLowerCase();
  if (!q) return [];

  if (/^\d+$/.test(q)) {
    return HSN_DATA.filter((h) => h.code.startsWith(q)).slice(0, limit);
  }

  const terms = q.split(/\s+/);
  const scored = [];
  for (const item of HSN_DATA) {
    const lower = lowerFields(item);
    let matched = 0;
    for (const term of terms) {
      if (lower.desc.includes(term) || lower.category.includes(term) || lower.code.includes(term)) {
        matched++;
      }
    }
    if (matched === terms.length) {
      scored.push(item);
    }
  }
  return scored.slice(0, limit);
}

export function getByCode(code) {
  return HSN_DATA.find((h) => h.code === code) || null;
}

export function categories() {
  return [...new Set(HSN_DATA.map((h) => h.category))].sort();
}

export function byCategory(category) {
  return HSN_DATA.filter((h) => h.category === category);
}

const PRODUCT_RATES = [
  { product: "rice", hsn: "1006", rate: 5 },
  { product: "wheat", hsn: "1001", rate: 0 },
  { product: "wheat flour", hsn: "1101", rate: 0 },
  { product: "atta", hsn: "1101", rate: 0 },
  { product: "sugar", hsn: "1701", rate: 5 },
  { product: "milk", hsn: "0401", rate: 0 },
  { product: "tea", hsn: "0902", rate: 5 },
  { product: "coffee", hsn: "0901", rate: 5 },
  { product: "dal", hsn: "0713", rate: 0 },
  { product: "lentils", hsn: "0713", rate: 0 },
  { product: "biscuits", hsn: "1905", rate: 18 },
  { product: "bread", hsn: "1905", rate: 18 },
  { product: "chocolate", hsn: "1806", rate: 18 },
  { product: "soft drinks", hsn: "2202", rate: 40 },
  { product: "cold drinks", hsn: "2202", rate: 40 },
  { product: "cola", hsn: "2202", rate: 40 },
  { product: "bottled water", hsn: "2201", rate: 18 },
  { product: "mineral water", hsn: "2201", rate: 18 },
  { product: "cement", hsn: "2523", rate: 18 },
  { product: "medicine", hsn: "3004", rate: 5 },
  { product: "medicines", hsn: "3004", rate: 5 },
  { product: "drugs", hsn: "3004", rate: 5 },
  { product: "toothpaste", hsn: "3306", rate: 18 },
  { product: "shampoo", hsn: "3305", rate: 18 },
  { product: "soap", hsn: "3401", rate: 18 },
  { product: "detergent", hsn: "3402", rate: 18 },
  { product: "paint", hsn: "3208", rate: 18 },
  { product: "plastic bags", hsn: "3923", rate: 18 },
  { product: "plastic bottles", hsn: "3923", rate: 18 },
  { product: "tyres", hsn: "4011", rate: 18 },
  { product: "tires", hsn: "4011", rate: 18 },
  { product: "books", hsn: "4901", rate: 0 },
  { product: "newspapers", hsn: "4902", rate: 0 },
  { product: "cotton fabric", hsn: "5208", rate: 5 },
  { product: "silk fabric", hsn: "5007", rate: 5 },
  { product: "t-shirts", hsn: "6109", rate: 5 },
  { product: "shirts", hsn: "6205", rate: 5 },
  { product: "jeans", hsn: "6203", rate: 5 },
  { product: "trousers", hsn: "6203", rate: 5 },
  { product: "dresses", hsn: "6204", rate: 5 },
  { product: "shoes", hsn: "6403", rate: 18 },
  { product: "footwear", hsn: "6402", rate: 18 },
  { product: "sandals", hsn: "6402", rate: 18 },
  { product: "ceramic tiles", hsn: "6907", rate: 18 },
  { product: "tiles", hsn: "6907", rate: 18 },
  { product: "marble", hsn: "6802", rate: 18 },
  { product: "granite", hsn: "6802", rate: 18 },
  { product: "gold jewellery", hsn: "7113", rate: 3 },
  { product: "silver jewellery", hsn: "7113", rate: 3 },
  { product: "jewellery", hsn: "7113", rate: 3 },
  { product: "steel", hsn: "7210", rate: 18 },
  { product: "iron", hsn: "7214", rate: 18 },
  { product: "air conditioner", hsn: "8415", rate: 18 },
  { product: "ac", hsn: "8415", rate: 18 },
  { product: "refrigerator", hsn: "8418", rate: 18 },
  { product: "fridge", hsn: "8418", rate: 18 },
  { product: "washing machine", hsn: "8450", rate: 18 },
  { product: "laptop", hsn: "8471", rate: 18 },
  { product: "computer", hsn: "8471", rate: 18 },
  { product: "desktop", hsn: "8471", rate: 18 },
  { product: "printer", hsn: "8443", rate: 18 },
  { product: "mobile phone", hsn: "8517", rate: 18 },
  { product: "smartphone", hsn: "8517", rate: 18 },
  { product: "phone", hsn: "8517", rate: 18 },
  { product: "headphones", hsn: "8518", rate: 18 },
  { product: "earphones", hsn: "8518", rate: 18 },
  { product: "speaker", hsn: "8518", rate: 18 },
  { product: "television", hsn: "8528", rate: 18 },
  { product: "tv", hsn: "8528", rate: 18 },
  { product: "monitor", hsn: "8528", rate: 18 },
  { product: "led bulb", hsn: "8539", rate: 5 },
  { product: "car", hsn: "8703", rate: 18 },
  { product: "motor car", hsn: "8703", rate: 18 },
  { product: "suv", hsn: "8703", rate: 18 },
  { product: "motorcycle", hsn: "8711", rate: 18 },
  { product: "bike", hsn: "8711", rate: 18 },
  { product: "scooter", hsn: "8711", rate: 18 },
  { product: "bicycle", hsn: "8712", rate: 5 },
  { product: "spectacles", hsn: "9004", rate: 18 },
  { product: "sunglasses", hsn: "9004", rate: 18 },
  { product: "glasses", hsn: "9004", rate: 18 },
  { product: "furniture", hsn: "9403", rate: 18 },
  { product: "chair", hsn: "9401", rate: 18 },
  { product: "sofa", hsn: "9401", rate: 18 },
  { product: "table", hsn: "9403", rate: 18 },
  { product: "desk", hsn: "9403", rate: 18 },
  { product: "mattress", hsn: "9404", rate: 18 },
  { product: "toys", hsn: "9503", rate: 5 },
  { product: "pen", hsn: "9608", rate: 18 },
  { product: "pencil", hsn: "9609", rate: 5 },
  { product: "diapers", hsn: "9619", rate: 5 },
  { product: "sanitary pads", hsn: "9619", rate: 5 },
  { product: "it services", hsn: "9983", rate: 18 },
  { product: "consulting", hsn: "9983", rate: 18 },
  { product: "software services", hsn: "9983", rate: 18 },
  { product: "legal services", hsn: "9982", rate: 18 },
  { product: "accounting services", hsn: "9982", rate: 18 },
  { product: "ca services", hsn: "9982", rate: 18 },
  { product: "construction services", hsn: "9954", rate: 18 },
  { product: "cab", hsn: "9964", rate: 5 },
  { product: "taxi", hsn: "9964", rate: 5 },
  { product: "uber", hsn: "9964", rate: 5 },
  { product: "ola", hsn: "9964", rate: 5 },
  { product: "freight", hsn: "9965", rate: 5 },
  { product: "courier", hsn: "9965", rate: 5 },
  { product: "education", hsn: "9992", rate: 0 },
  { product: "tuition", hsn: "9992", rate: 0 },
  { product: "hospital", hsn: "9993", rate: 0 },
  { product: "healthcare", hsn: "9993", rate: 0 },
  { product: "insurance", hsn: "9961", rate: 18 },
  { product: "banking", hsn: "9962", rate: 18 },
  { product: "gym", hsn: "9996", rate: 18 },
  { product: "salon", hsn: "9997", rate: 18 },
  { product: "laundry", hsn: "9997", rate: 18 },
  { product: "rent", hsn: "9972", rate: 18 },
  { product: "oil", hsn: "1515", rate: 5 },
  { product: "cooking oil", hsn: "1515", rate: 5 },
  { product: "sunflower oil", hsn: "1512", rate: 5 },
  { product: "palm oil", hsn: "1511", rate: 5 },
  { product: "soybean oil", hsn: "1507", rate: 5 },
  { product: "potato", hsn: "0701", rate: 0 },
  { product: "tomato", hsn: "0702", rate: 0 },
  { product: "vegetables", hsn: "0702", rate: 0 },
  { product: "cheese", hsn: "0406", rate: 5 },
  { product: "paneer", hsn: "0406", rate: 5 },
  { product: "ghee", hsn: "0405", rate: 5 },
  { product: "butter", hsn: "0405", rate: 5 },
  { product: "curd", hsn: "0403", rate: 0 },
  { product: "yogurt", hsn: "0403", rate: 0 },
  { product: "cream", hsn: "0401", rate: 0 },
  { product: "honey", hsn: "0409", rate: 0 },
  { product: "eggs", hsn: "0407", rate: 0 },
  { product: "chicken", hsn: "0207", rate: 0 },
  { product: "mutton", hsn: "0204", rate: 0 },
  { product: "fish", hsn: "0302", rate: 0 },
  { product: "prawns", hsn: "0306", rate: 0 },
  { product: "shrimp", hsn: "0306", rate: 0 },
  { product: "onion", hsn: "0703", rate: 0 },
  { product: "garlic", hsn: "0703", rate: 0 },
  { product: "ginger", hsn: "0910", rate: 5 },
  { product: "turmeric", hsn: "0910", rate: 5 },
  { product: "spices", hsn: "0910", rate: 5 },
  { product: "chilli", hsn: "0904", rate: 5 },
  { product: "pepper", hsn: "0904", rate: 5 },
  { product: "salt", hsn: "2501", rate: 0 },
  { product: "jaggery", hsn: "1701", rate: 0 },
  { product: "maida", hsn: "1101", rate: 0 },
  { product: "semolina", hsn: "1103", rate: 0 },
  { product: "suji", hsn: "1103", rate: 0 },
  { product: "noodles", hsn: "1902", rate: 18 },
  { product: "pasta", hsn: "1902", rate: 18 },
  { product: "chips", hsn: "2005", rate: 18 },
  { product: "namkeen", hsn: "2106", rate: 18 },
  { product: "papad", hsn: "2106", rate: 0 },
  { product: "pickles", hsn: "2001", rate: 18 },
  { product: "jam", hsn: "2007", rate: 18 },
  { product: "ketchup", hsn: "2103", rate: 18 },
  { product: "sauce", hsn: "2103", rate: 18 },
  { product: "ice cream", hsn: "2105", rate: 18 },
  { product: "juice", hsn: "2009", rate: 18 },
  { product: "fruit juice", hsn: "2009", rate: 18 },
  { product: "coconut oil", hsn: "1513", rate: 5 },
  { product: "mustard oil", hsn: "1514", rate: 5 },
  { product: "cigarettes", hsn: "2402", rate: 40 },
  { product: "tobacco", hsn: "2401", rate: 40 },
  { product: "petrol", hsn: "2710", rate: 18 },
  { product: "diesel", hsn: "2710", rate: 18 },
  { product: "lpg", hsn: "2711", rate: 5 },
  { product: "natural gas", hsn: "2711", rate: 5 },
  { product: "perfume", hsn: "3303", rate: 18 },
  { product: "deodorant", hsn: "3307", rate: 18 },
  { product: "cosmetics", hsn: "3304", rate: 18 },
  { product: "lipstick", hsn: "3304", rate: 18 },
  { product: "face cream", hsn: "3304", rate: 18 },
  { product: "sunscreen", hsn: "3304", rate: 18 },
  { product: "hair oil", hsn: "3305", rate: 18 },
  { product: "conditioner", hsn: "3305", rate: 18 },
  { product: "hand wash", hsn: "3401", rate: 18 },
  { product: "sanitizer", hsn: "3808", rate: 18 },
  { product: "disinfectant", hsn: "3808", rate: 18 },
  { product: "mosquito repellent", hsn: "3808", rate: 18 },
  { product: "fertilizer", hsn: "3105", rate: 5 },
  { product: "pesticide", hsn: "3808", rate: 18 },
  { product: "pvc pipe", hsn: "3917", rate: 18 },
  { product: "plastic sheet", hsn: "3920", rate: 18 },
  { product: "rubber", hsn: "4001", rate: 5 },
  { product: "handbag", hsn: "4202", rate: 18 },
  { product: "wallet", hsn: "4202", rate: 18 },
  { product: "belt", hsn: "4203", rate: 5 },
  { product: "suitcase", hsn: "4202", rate: 18 },
  { product: "backpack", hsn: "4202", rate: 18 },
  { product: "paper", hsn: "4802", rate: 5 },
  { product: "notebook", hsn: "4820", rate: 5 },
  { product: "diary", hsn: "4820", rate: 5 },
  { product: "cardboard box", hsn: "4819", rate: 18 },
  { product: "tissue paper", hsn: "4818", rate: 18 },
  { product: "saree", hsn: "5208", rate: 5 },
  { product: "kurta", hsn: "6205", rate: 5 },
  { product: "salwar", hsn: "6204", rate: 5 },
  { product: "jacket", hsn: "6101", rate: 5 },
  { product: "sweater", hsn: "6110", rate: 5 },
  { product: "socks", hsn: "6115", rate: 5 },
  { product: "undergarments", hsn: "6108", rate: 5 },
  { product: "towel", hsn: "6302", rate: 5 },
  { product: "bedsheet", hsn: "6304", rate: 5 },
  { product: "curtain", hsn: "6303", rate: 5 },
  { product: "carpet", hsn: "5701", rate: 5 },
  { product: "rug", hsn: "5701", rate: 5 },
  { product: "helmet", hsn: "6506", rate: 18 },
  { product: "cap", hsn: "6505", rate: 18 },
  { product: "hat", hsn: "6505", rate: 18 },
  { product: "umbrella", hsn: "6601", rate: 18 },
  { product: "bricks", hsn: "6901", rate: 5 },
  { product: "cement blocks", hsn: "6810", rate: 18 },
  { product: "sanitary ware", hsn: "6910", rate: 18 },
  { product: "glass", hsn: "7005", rate: 18 },
  { product: "mirror", hsn: "7009", rate: 18 },
  { product: "gold", hsn: "7108", rate: 3 },
  { product: "silver", hsn: "7106", rate: 3 },
  { product: "diamond", hsn: "7102", rate: 0.25 },
  { product: "platinum", hsn: "7110", rate: 3 },
  { product: "stainless steel", hsn: "7219", rate: 18 },
  { product: "aluminium", hsn: "7601", rate: 18 },
  { product: "copper", hsn: "7403", rate: 18 },
  { product: "brass", hsn: "7403", rate: 18 },
  { product: "steel pipe", hsn: "7306", rate: 18 },
  { product: "steel rod", hsn: "7213", rate: 18 },
  { product: "tmt bar", hsn: "7214", rate: 18 },
  { product: "nuts and bolts", hsn: "7318", rate: 18 },
  { product: "wire", hsn: "7217", rate: 18 },
  { product: "nail", hsn: "7317", rate: 18 },
  { product: "lock", hsn: "8301", rate: 18 },
  { product: "fan", hsn: "8414", rate: 18 },
  { product: "ceiling fan", hsn: "8414", rate: 18 },
  { product: "water heater", hsn: "8516", rate: 18 },
  { product: "geyser", hsn: "8516", rate: 18 },
  { product: "iron box", hsn: "8516", rate: 18 },
  { product: "mixer grinder", hsn: "8509", rate: 18 },
  { product: "microwave", hsn: "8516", rate: 18 },
  { product: "oven", hsn: "8516", rate: 18 },
  { product: "water purifier", hsn: "8421", rate: 18 },
  { product: "inverter", hsn: "8504", rate: 18 },
  { product: "ups", hsn: "8504", rate: 18 },
  { product: "battery", hsn: "8507", rate: 18 },
  { product: "solar panel", hsn: "8541", rate: 18 },
  { product: "cable", hsn: "8544", rate: 18 },
  { product: "switch", hsn: "8536", rate: 18 },
  { product: "cctv camera", hsn: "8525", rate: 18 },
  { product: "router", hsn: "8517", rate: 18 },
  { product: "tablet", hsn: "8471", rate: 18 },
  { product: "ipad", hsn: "8471", rate: 18 },
  { product: "pen drive", hsn: "8523", rate: 18 },
  { product: "hard disk", hsn: "8471", rate: 18 },
  { product: "keyboard", hsn: "8471", rate: 18 },
  { product: "mouse", hsn: "8471", rate: 18 },
  { product: "projector", hsn: "8528", rate: 18 },
  { product: "camera", hsn: "8525", rate: 18 },
  { product: "smartwatch", hsn: "9102", rate: 18 },
  { product: "watch", hsn: "9101", rate: 18 },
  { product: "wristwatch", hsn: "9101", rate: 18 },
  { product: "electric vehicle", hsn: "8703", rate: 5 },
  { product: "ev", hsn: "8703", rate: 5 },
  { product: "auto rickshaw", hsn: "8703", rate: 18 },
  { product: "tractor", hsn: "8701", rate: 5 },
  { product: "truck", hsn: "8704", rate: 18 },
  { product: "bus", hsn: "8702", rate: 18 },
  { product: "ambulance", hsn: "8703", rate: 18 },
  { product: "stethoscope", hsn: "9018", rate: 5 },
  { product: "wheelchair", hsn: "8713", rate: 0 },
  { product: "hearing aid", hsn: "9021", rate: 0 },
  { product: "contact lens", hsn: "9001", rate: 18 },
  { product: "bed", hsn: "9403", rate: 18 },
  { product: "wardrobe", hsn: "9403", rate: 18 },
  { product: "dining table", hsn: "9403", rate: 18 },
  { product: "bookshelf", hsn: "9403", rate: 18 },
  { product: "lamp", hsn: "9405", rate: 18 },
  { product: "chandelier", hsn: "9405", rate: 18 },
  { product: "pillow", hsn: "9404", rate: 18 },
  { product: "cricket bat", hsn: "9506", rate: 5 },
  { product: "football", hsn: "9506", rate: 5 },
  { product: "badminton racket", hsn: "9506", rate: 5 },
  { product: "chess", hsn: "9504", rate: 18 },
  { product: "video game", hsn: "9504", rate: 18 },
  { product: "playing cards", hsn: "9504", rate: 18 },
  { product: "doll", hsn: "9503", rate: 5 },
  { product: "board game", hsn: "9504", rate: 18 },
  { product: "eraser", hsn: "4016", rate: 18 },
  { product: "stapler", hsn: "8305", rate: 18 },
  { product: "scissors", hsn: "8213", rate: 18 },
  { product: "tape", hsn: "3919", rate: 18 },
  { product: "glue", hsn: "3506", rate: 18 },
  { product: "parachute", hsn: "8804", rate: 18 },
  { product: "hotel room", hsn: "9963", rate: 18 },
  { product: "restaurant food", hsn: "9963", rate: 5 },
  { product: "catering", hsn: "9963", rate: 5 },
  { product: "movie ticket", hsn: "9996", rate: 18 },
  { product: "event ticket", hsn: "9996", rate: 18 },
  { product: "security services", hsn: "9985", rate: 18 },
  { product: "cleaning services", hsn: "9985", rate: 18 },
  { product: "transport", hsn: "9965", rate: 5 },
  { product: "logistics", hsn: "9965", rate: 5 },
  { product: "warehousing", hsn: "9967", rate: 18 },
  { product: "advertising", hsn: "9983", rate: 18 },
  { product: "web development", hsn: "9983", rate: 18 },
  { product: "app development", hsn: "9983", rate: 18 },
  { product: "cloud hosting", hsn: "9984", rate: 18 },
  { product: "internet", hsn: "9984", rate: 18 },
  { product: "broadband", hsn: "9984", rate: 18 },
  { product: "mobile recharge", hsn: "9984", rate: 18 },
  { product: "electricity", hsn: "2716", rate: 18 },
  { product: "real estate", hsn: "9972", rate: 18 },
  { product: "flat", hsn: "9972", rate: 18 },
  { product: "apartment", hsn: "9972", rate: 18 },
  { product: "life insurance", hsn: "9961", rate: 18 },
  { product: "health insurance", hsn: "9961", rate: 18 },
  { product: "motor insurance", hsn: "9961", rate: 18 },
  { product: "mutual fund", hsn: "9971", rate: 18 },
  { product: "stock broking", hsn: "9971", rate: 18 },
  { product: "chartered accountant", hsn: "9982", rate: 18 },
  { product: "audit services", hsn: "9982", rate: 18 },
  { product: "architect services", hsn: "9983", rate: 18 },
  { product: "photography", hsn: "9983", rate: 18 },
  { product: "printing services", hsn: "9989", rate: 18 },
  { product: "courier services", hsn: "9965", rate: 18 },
  { product: "dry cleaning", hsn: "9997", rate: 18 },
  { product: "tailoring", hsn: "9997", rate: 18 },
  { product: "beauty parlour", hsn: "9997", rate: 18 },
  { product: "spa", hsn: "9997", rate: 18 },
  { product: "yoga classes", hsn: "9996", rate: 18 },
  { product: "coaching", hsn: "9992", rate: 18 },
  { product: "training", hsn: "9992", rate: 18 },
];

export function findProductRate(product) {
  const q = (product || "").trim().toLowerCase().replace(/-/g, " ");
  if (!q) return null;
  const exact = PRODUCT_RATES.find((p) => p.product === q);
  if (exact) return exact;
  return PRODUCT_RATES.find((p) => q.includes(p.product) || p.product.includes(q)) || null;
}

export function allProducts() {
  return PRODUCT_RATES;
}

export function relatedProducts(product, { limit = 5 } = {}) {
  const match = findProductRate(product);
  if (!match) return PRODUCT_RATES.slice(0, limit);
  const hsn = getByCode(match.hsn);
  const category = hsn ? hsn.category : null;
  const seen = new Set([match.product]);
  const results = [];
  for (const p of PRODUCT_RATES) {
    if (seen.has(p.product)) continue;
    if (p.hsn === match.hsn || p.rate === match.rate) {
      const ph = getByCode(p.hsn);
      if (ph && category && ph.category === category) {
        results.unshift(p);
      } else {
        results.push(p);
      }
      seen.add(p.product);
    }
    if (results.length >= limit * 2) break;
  }
  return results.slice(0, limit);
}

export { HSN_DATA };
