const HSN_DATA = [
  { code: "0201", desc: "Meat of bovine animals, fresh or chilled", rate: 0, category: "Food" },
  { code: "0401", desc: "Milk and cream, not concentrated", rate: 0, category: "Food" },
  { code: "0402", desc: "Milk and cream, concentrated or sweetened", rate: 5, category: "Food" },
  { code: "0406", desc: "Cheese and curd", rate: 12, category: "Food" },
  { code: "0701", desc: "Potatoes, fresh or chilled", rate: 0, category: "Food" },
  { code: "0702", desc: "Tomatoes, fresh or chilled", rate: 0, category: "Food" },
  { code: "0713", desc: "Dried leguminous vegetables (dal, lentils)", rate: 0, category: "Food" },
  { code: "0901", desc: "Coffee, whether or not roasted", rate: 5, category: "Food" },
  { code: "0902", desc: "Tea, whether or not flavoured", rate: 5, category: "Food" },
  { code: "1001", desc: "Wheat and meslin", rate: 0, category: "Food" },
  { code: "1005", desc: "Maize (corn)", rate: 0, category: "Food" },
  { code: "1006", desc: "Rice", rate: 5, category: "Food" },
  { code: "1101", desc: "Wheat or meslin flour (atta)", rate: 0, category: "Food" },
  { code: "1501", desc: "Animal fats and oils", rate: 12, category: "Food" },
  { code: "1507", desc: "Soya-bean oil", rate: 5, category: "Food" },
  { code: "1511", desc: "Palm oil", rate: 5, category: "Food" },
  { code: "1512", desc: "Sunflower oil, safflower oil", rate: 5, category: "Food" },
  { code: "1515", desc: "Groundnut oil, olive oil, other fixed vegetable oils", rate: 5, category: "Food" },
  { code: "1701", desc: "Cane or beet sugar", rate: 5, category: "Food" },
  { code: "1704", desc: "Sugar confectionery (not containing cocoa)", rate: 18, category: "Food" },
  { code: "1806", desc: "Chocolate and other food preparations containing cocoa", rate: 18, category: "Food" },
  { code: "1901", desc: "Malt extract; food preparations of flour", rate: 18, category: "Food" },
  { code: "1905", desc: "Bread, biscuits, cakes, pastry", rate: 18, category: "Food" },
  { code: "2106", desc: "Food preparations not elsewhere specified (namkeen, papad)", rate: 12, category: "Food" },
  { code: "2201", desc: "Waters, including mineral and aerated waters", rate: 18, category: "Beverages" },
  { code: "2202", desc: "Sweetened or flavoured water, soft drinks", rate: 28, category: "Beverages" },
  { code: "2402", desc: "Cigars, cigarettes, tobacco", rate: 28, category: "Tobacco" },
  { code: "2523", desc: "Portland cement, aluminous cement", rate: 28, category: "Construction" },
  { code: "2710", desc: "Petroleum oils (petrol, diesel, ATF)", rate: 18, category: "Fuel" },
  { code: "2711", desc: "Petroleum gases (LPG, natural gas)", rate: 5, category: "Fuel" },
  { code: "3004", desc: "Medicaments (medicines for therapeutic use)", rate: 12, category: "Pharma" },
  { code: "3005", desc: "Bandages, dressings, medical supplies", rate: 12, category: "Pharma" },
  { code: "3006", desc: "Pharmaceutical preparations (surgical sutures, blood-grouping reagents)", rate: 12, category: "Pharma" },
  { code: "3204", desc: "Synthetic colouring matter; dyes", rate: 18, category: "Chemicals" },
  { code: "3208", desc: "Paints and varnishes", rate: 28, category: "Chemicals" },
  { code: "3213", desc: "Artists' colours", rate: 18, category: "Chemicals" },
  { code: "3304", desc: "Beauty or make-up preparations, skincare", rate: 28, category: "Cosmetics" },
  { code: "3305", desc: "Hair care preparations (shampoo, conditioner)", rate: 18, category: "Cosmetics" },
  { code: "3306", desc: "Oral or dental hygiene preparations (toothpaste)", rate: 18, category: "Cosmetics" },
  { code: "3401", desc: "Soap, washing preparations, detergent", rate: 18, category: "Household" },
  { code: "3402", desc: "Cleaning preparations, surface-active agents", rate: 18, category: "Household" },
  { code: "3808", desc: "Insecticides, fungicides, herbicides", rate: 18, category: "Chemicals" },
  { code: "3917", desc: "Tubes, pipes and hoses of plastics", rate: 18, category: "Plastics" },
  { code: "3920", desc: "Plastic plates, sheets, film (packaging)", rate: 18, category: "Plastics" },
  { code: "3923", desc: "Plastic containers, bottles, bags", rate: 18, category: "Plastics" },
  { code: "3926", desc: "Other articles of plastics", rate: 18, category: "Plastics" },
  { code: "4011", desc: "New pneumatic tyres of rubber", rate: 28, category: "Rubber" },
  { code: "4202", desc: "Trunks, suitcases, handbags, wallets", rate: 18, category: "Leather" },
  { code: "4203", desc: "Leather garments, gloves, belts", rate: 12, category: "Leather" },
  { code: "4802", desc: "Paper and paperboard, uncoated", rate: 12, category: "Paper" },
  { code: "4811", desc: "Paper, coated, impregnated", rate: 18, category: "Paper" },
  { code: "4819", desc: "Cartons, boxes, bags of paper", rate: 18, category: "Paper" },
  { code: "4820", desc: "Registers, notebooks, diaries", rate: 12, category: "Paper" },
  { code: "4901", desc: "Printed books, brochures, leaflets", rate: 0, category: "Paper" },
  { code: "4902", desc: "Newspapers, journals, periodicals", rate: 0, category: "Paper" },
  { code: "5007", desc: "Woven fabrics of silk", rate: 5, category: "Textiles" },
  { code: "5208", desc: "Woven fabrics of cotton", rate: 5, category: "Textiles" },
  { code: "5209", desc: "Woven fabrics of cotton (above 200g/m2)", rate: 5, category: "Textiles" },
  { code: "5407", desc: "Woven fabrics of synthetic filament yarn", rate: 5, category: "Textiles" },
  { code: "5513", desc: "Woven fabrics of synthetic staple fibres", rate: 5, category: "Textiles" },
  { code: "6101", desc: "Men's overcoats, jackets (knitted)", rate: 12, category: "Garments" },
  { code: "6104", desc: "Women's suits, dresses, skirts (knitted)", rate: 12, category: "Garments" },
  { code: "6109", desc: "T-shirts, singlets, vests (knitted)", rate: 12, category: "Garments" },
  { code: "6110", desc: "Jerseys, pullovers, cardigans (knitted)", rate: 12, category: "Garments" },
  { code: "6203", desc: "Men's suits, trousers, shorts", rate: 12, category: "Garments" },
  { code: "6204", desc: "Women's suits, trousers, shorts", rate: 12, category: "Garments" },
  { code: "6205", desc: "Men's shirts", rate: 12, category: "Garments" },
  { code: "6206", desc: "Women's blouses, shirts", rate: 12, category: "Garments" },
  { code: "6401", desc: "Waterproof footwear", rate: 18, category: "Footwear" },
  { code: "6402", desc: "Footwear with outer soles of rubber or plastics", rate: 18, category: "Footwear" },
  { code: "6403", desc: "Footwear with leather uppers", rate: 18, category: "Footwear" },
  { code: "6802", desc: "Worked monumental stone, marble, granite", rate: 28, category: "Construction" },
  { code: "6907", desc: "Ceramic tiles for floors and walls", rate: 18, category: "Construction" },
  { code: "6910", desc: "Ceramic sinks, wash basins, baths, toilets", rate: 18, category: "Construction" },
  { code: "6911", desc: "Tableware, kitchenware of porcelain", rate: 12, category: "Household" },
  { code: "7005", desc: "Float glass, polished glass in sheets", rate: 18, category: "Construction" },
  { code: "7013", desc: "Glassware for table, kitchen use", rate: 18, category: "Household" },
  { code: "7113", desc: "Jewellery of precious metal", rate: 3, category: "Jewellery" },
  { code: "7114", desc: "Articles of goldsmiths' or silversmiths' wares", rate: 3, category: "Jewellery" },
  { code: "7117", desc: "Imitation jewellery", rate: 18, category: "Jewellery" },
  { code: "7210", desc: "Hot rolled / cold rolled steel sheets", rate: 18, category: "Metals" },
  { code: "7213", desc: "Hot-rolled bars and rods of iron or steel", rate: 18, category: "Metals" },
  { code: "7214", desc: "Iron or non-alloy steel bars, rods", rate: 18, category: "Metals" },
  { code: "7306", desc: "Steel tubes, pipes, hollow profiles", rate: 18, category: "Metals" },
  { code: "7308", desc: "Structures and parts of iron or steel", rate: 18, category: "Metals" },
  { code: "7318", desc: "Screws, bolts, nuts, washers of iron", rate: 18, category: "Metals" },
  { code: "7321", desc: "Stoves, cookers, grills (iron or steel)", rate: 18, category: "Household" },
  { code: "7323", desc: "Table, kitchen articles of iron or steel", rate: 18, category: "Household" },
  { code: "7615", desc: "Aluminium table, kitchen articles", rate: 12, category: "Household" },
  { code: "8407", desc: "Spark-ignition internal combustion engines", rate: 28, category: "Machinery" },
  { code: "8414", desc: "Air pumps, vacuum pumps, compressors, fans", rate: 18, category: "Machinery" },
  { code: "8415", desc: "Air conditioning machines", rate: 28, category: "Machinery" },
  { code: "8418", desc: "Refrigerators, freezers", rate: 18, category: "Appliances" },
  { code: "8422", desc: "Dish washing machines", rate: 18, category: "Appliances" },
  { code: "8443", desc: "Printing machinery; printers, copiers", rate: 18, category: "Machinery" },
  { code: "8450", desc: "Washing machines", rate: 18, category: "Appliances" },
  { code: "8471", desc: "Computers and data processing machines", rate: 18, category: "Electronics" },
  { code: "8473", desc: "Parts and accessories for computers", rate: 18, category: "Electronics" },
  { code: "8501", desc: "Electric motors and generators", rate: 18, category: "Electronics" },
  { code: "8504", desc: "Electrical transformers, static converters, UPS", rate: 18, category: "Electronics" },
  { code: "8506", desc: "Primary cells and batteries", rate: 18, category: "Electronics" },
  { code: "8507", desc: "Electric accumulators (lithium-ion batteries)", rate: 18, category: "Electronics" },
  { code: "8516", desc: "Electric water heaters, hair dryers, irons", rate: 18, category: "Appliances" },
  { code: "8517", desc: "Telephone sets including smartphones", rate: 18, category: "Electronics" },
  { code: "8518", desc: "Microphones, speakers, headphones", rate: 18, category: "Electronics" },
  { code: "8521", desc: "Video recording or reproducing apparatus", rate: 18, category: "Electronics" },
  { code: "8523", desc: "Discs, tapes, solid-state storage devices (pen drives, memory cards)", rate: 18, category: "Electronics" },
  { code: "8525", desc: "Transmission apparatus; cameras, camcorders", rate: 18, category: "Electronics" },
  { code: "8528", desc: "Monitors and projectors; televisions", rate: 18, category: "Electronics" },
  { code: "8534", desc: "Printed circuits (PCBs)", rate: 18, category: "Electronics" },
  { code: "8536", desc: "Electrical switches, fuses, connectors", rate: 18, category: "Electronics" },
  { code: "8539", desc: "Electric filament or LED lamps", rate: 12, category: "Electronics" },
  { code: "8541", desc: "Semiconductor devices; LEDs; solar cells", rate: 18, category: "Electronics" },
  { code: "8544", desc: "Insulated wire, cable; optical fibre cables", rate: 18, category: "Electronics" },
  { code: "8703", desc: "Motor cars and vehicles (petrol/diesel/electric)", rate: 28, category: "Automobiles" },
  { code: "8711", desc: "Motorcycles and cycles with auxiliary motor", rate: 28, category: "Automobiles" },
  { code: "8712", desc: "Bicycles and other cycles (not motorized)", rate: 12, category: "Automobiles" },
  { code: "8714", desc: "Parts and accessories for motorcycles and bicycles", rate: 18, category: "Automobiles" },
  { code: "9001", desc: "Optical fibres and cables; lenses", rate: 18, category: "Optical" },
  { code: "9004", desc: "Spectacles, goggles, sunglasses", rate: 18, category: "Optical" },
  { code: "9018", desc: "Medical, surgical or dental instruments", rate: 12, category: "Medical" },
  { code: "9021", desc: "Orthopaedic appliances, hearing aids", rate: 12, category: "Medical" },
  { code: "9401", desc: "Seats and parts (chairs, sofas)", rate: 18, category: "Furniture" },
  { code: "9403", desc: "Other furniture (tables, desks, wardrobes)", rate: 18, category: "Furniture" },
  { code: "9404", desc: "Mattress supports; mattresses", rate: 18, category: "Furniture" },
  { code: "9405", desc: "Lamps and lighting fittings", rate: 18, category: "Furniture" },
  { code: "9503", desc: "Toys, games; tricycles, dolls", rate: 12, category: "Toys" },
  { code: "9504", desc: "Video game consoles, carrom boards, chess", rate: 18, category: "Toys" },
  { code: "9506", desc: "Sports equipment, gym articles", rate: 12, category: "Sports" },
  { code: "9608", desc: "Ball point pens, felt tipped pens", rate: 18, category: "Stationery" },
  { code: "9609", desc: "Pencils, crayons, chalk", rate: 12, category: "Stationery" },
  { code: "9619", desc: "Sanitary towels, napkins, diapers", rate: 12, category: "Health" },

  { code: "9954", desc: "Construction services", rate: 18, category: "Services", sac: true },
  { code: "9961", desc: "Financial and insurance services", rate: 18, category: "Services", sac: true },
  { code: "9962", desc: "Financial and related services (banking, lending)", rate: 18, category: "Services", sac: true },
  { code: "9963", desc: "Leasing or rental services", rate: 18, category: "Services", sac: true },
  { code: "9964", desc: "Passenger transport services", rate: 5, category: "Services", sac: true },
  { code: "9965", desc: "Goods transport services", rate: 5, category: "Services", sac: true },
  { code: "9966", desc: "Rental services of transport vehicles", rate: 18, category: "Services", sac: true },
  { code: "9971", desc: "Financial intermediation and related services", rate: 18, category: "Services", sac: true },
  { code: "9972", desc: "Real estate services", rate: 18, category: "Services", sac: true },
  { code: "9973", desc: "Leasing / rental without operator", rate: 18, category: "Services", sac: true },
  { code: "9981", desc: "Research and development services", rate: 18, category: "Services", sac: true },
  { code: "9982", desc: "Legal and accounting services", rate: 18, category: "Services", sac: true },
  { code: "9983", desc: "Other professional, technical, business services (IT, consulting)", rate: 18, category: "Services", sac: true },
  { code: "9984", desc: "Telecommunications, broadcasting services", rate: 18, category: "Services", sac: true },
  { code: "9985", desc: "Support services (security, cleaning, temp staffing)", rate: 18, category: "Services", sac: true },
  { code: "9986", desc: "Support services to agriculture, forestry", rate: 0, category: "Services", sac: true },
  { code: "9991", desc: "Public administration services", rate: 0, category: "Services", sac: true },
  { code: "9992", desc: "Education services", rate: 0, category: "Services", sac: true },
  { code: "9993", desc: "Health and social care services", rate: 0, category: "Services", sac: true },
  { code: "9995", desc: "Services of membership organisations", rate: 18, category: "Services", sac: true },
  { code: "9996", desc: "Recreational, cultural and sporting services", rate: 18, category: "Services", sac: true },
  { code: "9997", desc: "Other services (laundry, beauty, wellness, funeral)", rate: 18, category: "Services", sac: true },
];

const _lowerCache = new Map();

function lowerFields(item) {
  if (_lowerCache.has(item)) return _lowerCache.get(item);
  const entry = {
    code: item.code,
    desc: item.desc.toLowerCase(),
    category: item.category.toLowerCase(),
  };
  _lowerCache.set(item, entry);
  return entry;
}

export function searchHSN(query, { limit = 20 } = {}) {
  const q = (query || "").trim().toLowerCase();
  if (!q) return [];

  if (/^\d+$/.test(q)) {
    return HSN_DATA.filter((h) => h.code.startsWith(q)).slice(0, limit);
  }

  const terms = q.split(/\s+/);
  const scored = [];
  for (const item of HSN_DATA) {
    const lower = lowerFields(item);
    let matched = 0;
    for (const term of terms) {
      if (lower.desc.includes(term) || lower.category.includes(term) || lower.code.includes(term)) {
        matched++;
      }
    }
    if (matched === terms.length) {
      scored.push(item);
    }
  }
  return scored.slice(0, limit);
}

export function getByCode(code) {
  return HSN_DATA.find((h) => h.code === code) || null;
}

export function categories() {
  return [...new Set(HSN_DATA.map((h) => h.category))].sort();
}

export function byCategory(category) {
  return HSN_DATA.filter((h) => h.category === category);
}

const PRODUCT_RATES = [
  { product: "rice", hsn: "1006", rate: 5 },
  { product: "wheat", hsn: "1001", rate: 0 },
  { product: "wheat flour", hsn: "1101", rate: 0 },
  { product: "atta", hsn: "1101", rate: 0 },
  { product: "sugar", hsn: "1701", rate: 5 },
  { product: "milk", hsn: "0401", rate: 0 },
  { product: "tea", hsn: "0902", rate: 5 },
  { product: "coffee", hsn: "0901", rate: 5 },
  { product: "dal", hsn: "0713", rate: 0 },
  { product: "lentils", hsn: "0713", rate: 0 },
  { product: "biscuits", hsn: "1905", rate: 18 },
  { product: "bread", hsn: "1905", rate: 18 },
  { product: "chocolate", hsn: "1806", rate: 18 },
  { product: "soft drinks", hsn: "2202", rate: 28 },
  { product: "cold drinks", hsn: "2202", rate: 28 },
  { product: "cola", hsn: "2202", rate: 28 },
  { product: "bottled water", hsn: "2201", rate: 18 },
  { product: "mineral water", hsn: "2201", rate: 18 },
  { product: "cement", hsn: "2523", rate: 28 },
  { product: "medicine", hsn: "3004", rate: 12 },
  { product: "medicines", hsn: "3004", rate: 12 },
  { product: "drugs", hsn: "3004", rate: 12 },
  { product: "toothpaste", hsn: "3306", rate: 18 },
  { product: "shampoo", hsn: "3305", rate: 18 },
  { product: "soap", hsn: "3401", rate: 18 },
  { product: "detergent", hsn: "3402", rate: 18 },
  { product: "paint", hsn: "3208", rate: 28 },
  { product: "plastic bags", hsn: "3923", rate: 18 },
  { product: "plastic bottles", hsn: "3923", rate: 18 },
  { product: "tyres", hsn: "4011", rate: 28 },
  { product: "tires", hsn: "4011", rate: 28 },
  { product: "books", hsn: "4901", rate: 0 },
  { product: "newspapers", hsn: "4902", rate: 0 },
  { product: "cotton fabric", hsn: "5208", rate: 5 },
  { product: "silk fabric", hsn: "5007", rate: 5 },
  { product: "t-shirts", hsn: "6109", rate: 12 },
  { product: "shirts", hsn: "6205", rate: 12 },
  { product: "jeans", hsn: "6203", rate: 12 },
  { product: "trousers", hsn: "6203", rate: 12 },
  { product: "dresses", hsn: "6204", rate: 12 },
  { product: "shoes", hsn: "6403", rate: 18 },
  { product: "footwear", hsn: "6402", rate: 18 },
  { product: "sandals", hsn: "6402", rate: 18 },
  { product: "ceramic tiles", hsn: "6907", rate: 18 },
  { product: "tiles", hsn: "6907", rate: 18 },
  { product: "marble", hsn: "6802", rate: 28 },
  { product: "granite", hsn: "6802", rate: 28 },
  { product: "gold jewellery", hsn: "7113", rate: 3 },
  { product: "silver jewellery", hsn: "7113", rate: 3 },
  { product: "jewellery", hsn: "7113", rate: 3 },
  { product: "steel", hsn: "7210", rate: 18 },
  { product: "iron", hsn: "7214", rate: 18 },
  { product: "air conditioner", hsn: "8415", rate: 28 },
  { product: "ac", hsn: "8415", rate: 28 },
  { product: "refrigerator", hsn: "8418", rate: 18 },
  { product: "fridge", hsn: "8418", rate: 18 },
  { product: "washing machine", hsn: "8450", rate: 18 },
  { product: "laptop", hsn: "8471", rate: 18 },
  { product: "computer", hsn: "8471", rate: 18 },
  { product: "desktop", hsn: "8471", rate: 18 },
  { product: "printer", hsn: "8443", rate: 18 },
  { product: "mobile phone", hsn: "8517", rate: 18 },
  { product: "smartphone", hsn: "8517", rate: 18 },
  { product: "phone", hsn: "8517", rate: 18 },
  { product: "headphones", hsn: "8518", rate: 18 },
  { product: "earphones", hsn: "8518", rate: 18 },
  { product: "speaker", hsn: "8518", rate: 18 },
  { product: "television", hsn: "8528", rate: 18 },
  { product: "tv", hsn: "8528", rate: 18 },
  { product: "monitor", hsn: "8528", rate: 18 },
  { product: "led bulb", hsn: "8539", rate: 12 },
  { product: "car", hsn: "8703", rate: 28 },
  { product: "motor car", hsn: "8703", rate: 28 },
  { product: "suv", hsn: "8703", rate: 28 },
  { product: "motorcycle", hsn: "8711", rate: 28 },
  { product: "bike", hsn: "8711", rate: 28 },
  { product: "scooter", hsn: "8711", rate: 28 },
  { product: "bicycle", hsn: "8712", rate: 12 },
  { product: "spectacles", hsn: "9004", rate: 18 },
  { product: "sunglasses", hsn: "9004", rate: 18 },
  { product: "glasses", hsn: "9004", rate: 18 },
  { product: "furniture", hsn: "9403", rate: 18 },
  { product: "chair", hsn: "9401", rate: 18 },
  { product: "sofa", hsn: "9401", rate: 18 },
  { product: "table", hsn: "9403", rate: 18 },
  { product: "desk", hsn: "9403", rate: 18 },
  { product: "mattress", hsn: "9404", rate: 18 },
  { product: "toys", hsn: "9503", rate: 12 },
  { product: "pen", hsn: "9608", rate: 18 },
  { product: "pencil", hsn: "9609", rate: 12 },
  { product: "diapers", hsn: "9619", rate: 12 },
  { product: "sanitary pads", hsn: "9619", rate: 12 },
  { product: "it services", hsn: "9983", rate: 18 },
  { product: "consulting", hsn: "9983", rate: 18 },
  { product: "software services", hsn: "9983", rate: 18 },
  { product: "legal services", hsn: "9982", rate: 18 },
  { product: "accounting services", hsn: "9982", rate: 18 },
  { product: "ca services", hsn: "9982", rate: 18 },
  { product: "construction services", hsn: "9954", rate: 18 },
  { product: "cab", hsn: "9964", rate: 5 },
  { product: "taxi", hsn: "9964", rate: 5 },
  { product: "uber", hsn: "9964", rate: 5 },
  { product: "ola", hsn: "9964", rate: 5 },
  { product: "freight", hsn: "9965", rate: 5 },
  { product: "courier", hsn: "9965", rate: 5 },
  { product: "education", hsn: "9992", rate: 0 },
  { product: "tuition", hsn: "9992", rate: 0 },
  { product: "hospital", hsn: "9993", rate: 0 },
  { product: "healthcare", hsn: "9993", rate: 0 },
  { product: "insurance", hsn: "9961", rate: 18 },
  { product: "banking", hsn: "9962", rate: 18 },
  { product: "gym", hsn: "9996", rate: 18 },
  { product: "salon", hsn: "9997", rate: 18 },
  { product: "laundry", hsn: "9997", rate: 18 },
  { product: "rent", hsn: "9972", rate: 18 },
  { product: "oil", hsn: "1515", rate: 5 },
  { product: "cooking oil", hsn: "1515", rate: 5 },
  { product: "sunflower oil", hsn: "1512", rate: 5 },
  { product: "palm oil", hsn: "1511", rate: 5 },
  { product: "soybean oil", hsn: "1507", rate: 5 },
  { product: "potato", hsn: "0701", rate: 0 },
  { product: "tomato", hsn: "0702", rate: 0 },
  { product: "vegetables", hsn: "0702", rate: 0 },
  { product: "cheese", hsn: "0406", rate: 12 },
  { product: "paneer", hsn: "0406", rate: 12 },
  { product: "ghee", hsn: "0405", rate: 12 },
  { product: "butter", hsn: "0405", rate: 12 },
  { product: "curd", hsn: "0403", rate: 0 },
  { product: "yogurt", hsn: "0403", rate: 0 },
  { product: "cream", hsn: "0401", rate: 0 },
  { product: "honey", hsn: "0409", rate: 0 },
  { product: "eggs", hsn: "0407", rate: 0 },
  { product: "chicken", hsn: "0207", rate: 0 },
  { product: "mutton", hsn: "0204", rate: 0 },
  { product: "fish", hsn: "0302", rate: 0 },
  { product: "prawns", hsn: "0306", rate: 5 },
  { product: "shrimp", hsn: "0306", rate: 5 },
  { product: "onion", hsn: "0703", rate: 0 },
  { product: "garlic", hsn: "0703", rate: 0 },
  { product: "ginger", hsn: "0910", rate: 5 },
  { product: "turmeric", hsn: "0910", rate: 5 },
  { product: "spices", hsn: "0910", rate: 5 },
  { product: "chilli", hsn: "0904", rate: 5 },
  { product: "pepper", hsn: "0904", rate: 5 },
  { product: "salt", hsn: "2501", rate: 0 },
  { product: "jaggery", hsn: "1701", rate: 0 },
  { product: "maida", hsn: "1101", rate: 0 },
  { product: "semolina", hsn: "1103", rate: 0 },
  { product: "suji", hsn: "1103", rate: 0 },
  { product: "noodles", hsn: "1902", rate: 18 },
  { product: "pasta", hsn: "1902", rate: 18 },
  { product: "chips", hsn: "2005", rate: 12 },
  { product: "namkeen", hsn: "2106", rate: 12 },
  { product: "papad", hsn: "2106", rate: 0 },
  { product: "pickles", hsn: "2001", rate: 12 },
  { product: "jam", hsn: "2007", rate: 12 },
  { product: "ketchup", hsn: "2103", rate: 12 },
  { product: "sauce", hsn: "2103", rate: 12 },
  { product: "ice cream", hsn: "2105", rate: 18 },
  { product: "juice", hsn: "2009", rate: 12 },
  { product: "fruit juice", hsn: "2009", rate: 12 },
  { product: "coconut oil", hsn: "1513", rate: 5 },
  { product: "mustard oil", hsn: "1514", rate: 5 },
  { product: "cigarettes", hsn: "2402", rate: 28 },
  { product: "tobacco", hsn: "2401", rate: 28 },
  { product: "petrol", hsn: "2710", rate: 18 },
  { product: "diesel", hsn: "2710", rate: 18 },
  { product: "lpg", hsn: "2711", rate: 5 },
  { product: "natural gas", hsn: "2711", rate: 5 },
  { product: "perfume", hsn: "3303", rate: 28 },
  { product: "deodorant", hsn: "3307", rate: 28 },
  { product: "cosmetics", hsn: "3304", rate: 28 },
  { product: "lipstick", hsn: "3304", rate: 28 },
  { product: "face cream", hsn: "3304", rate: 28 },
  { product: "sunscreen", hsn: "3304", rate: 28 },
  { product: "hair oil", hsn: "3305", rate: 18 },
  { product: "conditioner", hsn: "3305", rate: 18 },
  { product: "hand wash", hsn: "3401", rate: 18 },
  { product: "sanitizer", hsn: "3808", rate: 18 },
  { product: "disinfectant", hsn: "3808", rate: 18 },
  { product: "mosquito repellent", hsn: "3808", rate: 18 },
  { product: "fertilizer", hsn: "3105", rate: 5 },
  { product: "pesticide", hsn: "3808", rate: 18 },
  { product: "pvc pipe", hsn: "3917", rate: 18 },
  { product: "plastic sheet", hsn: "3920", rate: 18 },
  { product: "rubber", hsn: "4001", rate: 5 },
  { product: "handbag", hsn: "4202", rate: 18 },
  { product: "wallet", hsn: "4202", rate: 18 },
  { product: "belt", hsn: "4203", rate: 12 },
  { product: "suitcase", hsn: "4202", rate: 18 },
  { product: "backpack", hsn: "4202", rate: 18 },
  { product: "paper", hsn: "4802", rate: 12 },
  { product: "notebook", hsn: "4820", rate: 12 },
  { product: "diary", hsn: "4820", rate: 12 },
  { product: "cardboard box", hsn: "4819", rate: 18 },
  { product: "tissue paper", hsn: "4818", rate: 18 },
  { product: "saree", hsn: "5208", rate: 5 },
  { product: "kurta", hsn: "6205", rate: 12 },
  { product: "salwar", hsn: "6204", rate: 12 },
  { product: "jacket", hsn: "6101", rate: 12 },
  { product: "sweater", hsn: "6110", rate: 12 },
  { product: "socks", hsn: "6115", rate: 12 },
  { product: "undergarments", hsn: "6108", rate: 12 },
  { product: "towel", hsn: "6302", rate: 12 },
  { product: "bedsheet", hsn: "6304", rate: 12 },
  { product: "curtain", hsn: "6303", rate: 12 },
  { product: "carpet", hsn: "5701", rate: 12 },
  { product: "rug", hsn: "5701", rate: 12 },
  { product: "helmet", hsn: "6506", rate: 18 },
  { product: "cap", hsn: "6505", rate: 12 },
  { product: "hat", hsn: "6505", rate: 12 },
  { product: "umbrella", hsn: "6601", rate: 12 },
  { product: "bricks", hsn: "6901", rate: 5 },
  { product: "cement blocks", hsn: "6810", rate: 28 },
  { product: "sanitary ware", hsn: "6910", rate: 18 },
  { product: "glass", hsn: "7005", rate: 18 },
  { product: "mirror", hsn: "7009", rate: 18 },
  { product: "gold", hsn: "7108", rate: 3 },
  { product: "silver", hsn: "7106", rate: 3 },
  { product: "diamond", hsn: "7102", rate: 0.25 },
  { product: "platinum", hsn: "7110", rate: 3 },
  { product: "stainless steel", hsn: "7219", rate: 18 },
  { product: "aluminium", hsn: "7601", rate: 18 },
  { product: "copper", hsn: "7403", rate: 18 },
  { product: "brass", hsn: "7403", rate: 18 },
  { product: "steel pipe", hsn: "7306", rate: 18 },
  { product: "steel rod", hsn: "7213", rate: 18 },
  { product: "tmt bar", hsn: "7214", rate: 18 },
  { product: "nuts and bolts", hsn: "7318", rate: 18 },
  { product: "wire", hsn: "7217", rate: 18 },
  { product: "nail", hsn: "7317", rate: 18 },
  { product: "lock", hsn: "8301", rate: 18 },
  { product: "fan", hsn: "8414", rate: 18 },
  { product: "ceiling fan", hsn: "8414", rate: 18 },
  { product: "water heater", hsn: "8516", rate: 18 },
  { product: "geyser", hsn: "8516", rate: 18 },
  { product: "iron box", hsn: "8516", rate: 18 },
  { product: "mixer grinder", hsn: "8509", rate: 18 },
  { product: "microwave", hsn: "8516", rate: 18 },
  { product: "oven", hsn: "8516", rate: 18 },
  { product: "water purifier", hsn: "8421", rate: 18 },
  { product: "inverter", hsn: "8504", rate: 18 },
  { product: "ups", hsn: "8504", rate: 18 },
  { product: "battery", hsn: "8507", rate: 18 },
  { product: "solar panel", hsn: "8541", rate: 12 },
  { product: "cable", hsn: "8544", rate: 18 },
  { product: "switch", hsn: "8536", rate: 18 },
  { product: "cctv camera", hsn: "8525", rate: 18 },
  { product: "router", hsn: "8517", rate: 18 },
  { product: "tablet", hsn: "8471", rate: 18 },
  { product: "ipad", hsn: "8471", rate: 18 },
  { product: "pen drive", hsn: "8523", rate: 18 },
  { product: "hard disk", hsn: "8471", rate: 18 },
  { product: "keyboard", hsn: "8471", rate: 18 },
  { product: "mouse", hsn: "8471", rate: 18 },
  { product: "projector", hsn: "8528", rate: 18 },
  { product: "camera", hsn: "8525", rate: 18 },
  { product: "smartwatch", hsn: "9102", rate: 18 },
  { product: "watch", hsn: "9101", rate: 18 },
  { product: "wristwatch", hsn: "9101", rate: 18 },
  { product: "electric vehicle", hsn: "8703", rate: 5 },
  { product: "ev", hsn: "8703", rate: 5 },
  { product: "auto rickshaw", hsn: "8703", rate: 28 },
  { product: "tractor", hsn: "8701", rate: 12 },
  { product: "truck", hsn: "8704", rate: 28 },
  { product: "bus", hsn: "8702", rate: 28 },
  { product: "ambulance", hsn: "8703", rate: 28 },
  { product: "stethoscope", hsn: "9018", rate: 12 },
  { product: "wheelchair", hsn: "8713", rate: 0 },
  { product: "hearing aid", hsn: "9021", rate: 0 },
  { product: "contact lens", hsn: "9001", rate: 12 },
  { product: "bed", hsn: "9403", rate: 18 },
  { product: "wardrobe", hsn: "9403", rate: 18 },
  { product: "dining table", hsn: "9403", rate: 18 },
  { product: "bookshelf", hsn: "9403", rate: 18 },
  { product: "lamp", hsn: "9405", rate: 18 },
  { product: "chandelier", hsn: "9405", rate: 18 },
  { product: "pillow", hsn: "9404", rate: 18 },
  { product: "cricket bat", hsn: "9506", rate: 12 },
  { product: "football", hsn: "9506", rate: 12 },
  { product: "badminton racket", hsn: "9506", rate: 12 },
  { product: "chess", hsn: "9504", rate: 18 },
  { product: "video game", hsn: "9504", rate: 18 },
  { product: "playing cards", hsn: "9504", rate: 18 },
  { product: "doll", hsn: "9503", rate: 12 },
  { product: "board game", hsn: "9504", rate: 18 },
  { product: "eraser", hsn: "4016", rate: 12 },
  { product: "stapler", hsn: "8305", rate: 18 },
  { product: "scissors", hsn: "8213", rate: 18 },
  { product: "tape", hsn: "3919", rate: 18 },
  { product: "glue", hsn: "3506", rate: 18 },
  { product: "parachute", hsn: "8804", rate: 18 },
  { product: "hotel room", hsn: "9963", rate: 12 },
  { product: "restaurant food", hsn: "9963", rate: 5 },
  { product: "catering", hsn: "9963", rate: 5 },
  { product: "movie ticket", hsn: "9996", rate: 18 },
  { product: "event ticket", hsn: "9996", rate: 18 },
  { product: "security services", hsn: "9985", rate: 18 },
  { product: "cleaning services", hsn: "9985", rate: 18 },
  { product: "transport", hsn: "9965", rate: 5 },
  { product: "logistics", hsn: "9965", rate: 5 },
  { product: "warehousing", hsn: "9967", rate: 18 },
  { product: "advertising", hsn: "9983", rate: 18 },
  { product: "web development", hsn: "9983", rate: 18 },
  { product: "app development", hsn: "9983", rate: 18 },
  { product: "cloud hosting", hsn: "9984", rate: 18 },
  { product: "internet", hsn: "9984", rate: 18 },
  { product: "broadband", hsn: "9984", rate: 18 },
  { product: "mobile recharge", hsn: "9984", rate: 18 },
  { product: "electricity", hsn: "2716", rate: 18 },
  { product: "real estate", hsn: "9972", rate: 12 },
  { product: "flat", hsn: "9972", rate: 12 },
  { product: "apartment", hsn: "9972", rate: 12 },
  { product: "life insurance", hsn: "9961", rate: 18 },
  { product: "health insurance", hsn: "9961", rate: 18 },
  { product: "motor insurance", hsn: "9961", rate: 18 },
  { product: "mutual fund", hsn: "9971", rate: 18 },
  { product: "stock broking", hsn: "9971", rate: 18 },
  { product: "chartered accountant", hsn: "9982", rate: 18 },
  { product: "audit services", hsn: "9982", rate: 18 },
  { product: "architect services", hsn: "9983", rate: 18 },
  { product: "photography", hsn: "9983", rate: 18 },
  { product: "printing services", hsn: "9989", rate: 18 },
  { product: "courier services", hsn: "9965", rate: 18 },
  { product: "dry cleaning", hsn: "9997", rate: 18 },
  { product: "tailoring", hsn: "9997", rate: 18 },
  { product: "beauty parlour", hsn: "9997", rate: 18 },
  { product: "spa", hsn: "9997", rate: 18 },
  { product: "yoga classes", hsn: "9996", rate: 18 },
  { product: "coaching", hsn: "9992", rate: 18 },
  { product: "training", hsn: "9992", rate: 18 },
];

export function findProductRate(product) {
  const q = (product || "").trim().toLowerCase().replace(/-/g, " ");
  if (!q) return null;
  const exact = PRODUCT_RATES.find((p) => p.product === q);
  if (exact) return exact;
  return PRODUCT_RATES.find((p) => q.includes(p.product) || p.product.includes(q)) || null;
}

export function allProducts() {
  return PRODUCT_RATES;
}

export function relatedProducts(product, { limit = 5 } = {}) {
  const match = findProductRate(product);
  if (!match) return PRODUCT_RATES.slice(0, limit);
  const hsn = getByCode(match.hsn);
  const category = hsn ? hsn.category : null;
  const seen = new Set([match.product]);
  const results = [];
  for (const p of PRODUCT_RATES) {
    if (seen.has(p.product)) continue;
    if (p.hsn === match.hsn || p.rate === match.rate) {
      const ph = getByCode(p.hsn);
      if (ph && category && ph.category === category) {
        results.unshift(p);
      } else {
        results.push(p);
      }
      seen.add(p.product);
    }
    if (results.length >= limit * 2) break;
  }
  return results.slice(0, limit);
}

export { HSN_DATA };
