"""Authentication primitives: password hashing and JWT access tokens."""
from __future__ import annotations

import secrets
import threading
from datetime import UTC, datetime, timedelta
from typing import Any

import bcrypt
from jose import JWTError, jwt

from app.core.config import settings

# bcrypt operates on at most 72 bytes; longer inputs must be truncated first.
_BCRYPT_MAX_BYTES = 72

# A hash of a password nobody knows, compared against when no account matched.
# Built on first use rather than at import: it costs a full bcrypt round, and
# paying that in every worker boot and every test collection to serve a branch
# most processes never take is the wrong trade. Guarded by a lock so two
# concurrent failed logins do not both pay for it.
_absent_hash: str | None = None
_absent_hash_lock = threading.Lock()


def _prepare(password: str) -> bytes:
    return password.encode("utf-8")[:_BCRYPT_MAX_BYTES]


def hash_password(password: str) -> str:
    """Return a bcrypt hash for a plaintext password."""
    return bcrypt.hashpw(_prepare(password), bcrypt.gensalt()).decode("utf-8")


def _absent_account_hash() -> str:
    """A real bcrypt hash to compare against when there is no account.

    Minted from a random secret, so it is not a hash of anything guessable and
    a comparison against it cannot succeed. It is generated by
    :func:`hash_password`, so it carries the same cost factor as a stored hash
    and therefore takes the same time to check.
    """
    global _absent_hash

    if _absent_hash is None:
        with _absent_hash_lock:
            if _absent_hash is None:
                _absent_hash = hash_password(secrets.token_urlsafe(32))
    return _absent_hash


def verify_password(plain: str, hashed: str | None) -> bool:
    """Check a plaintext password against a stored bcrypt hash.

    ``hashed`` is ``None`` when the lookup found no account. That case still
    runs a full bcrypt comparison — against :func:`_absent_account_hash` — and
    only then returns ``False``.

    Skipping the work there is the obvious implementation and it is a user
    enumeration oracle. bcrypt is deliberately slow: a login against an account
    that exists costs a few hundred milliseconds, and one against an address
    that does not would cost a database round trip. That gap is two orders of
    magnitude and is trivially measurable across the internet, which hands an
    attacker the "does this business have an account" answer that the identical
    401 body is written to withhold. Taking ``None`` here rather than leaving
    the caller to remember a separate dummy-verify call is what keeps the two
    paths the same length.
    """
    if hashed is None:
        hashed = _absent_account_hash()
    try:
        return bcrypt.checkpw(_prepare(plain), hashed.encode("utf-8"))
    except (ValueError, TypeError):
        return False


def create_access_token(subject: str | int, expires_minutes: int | None = None) -> str:
    """Create a signed JWT whose ``sub`` claim is the user id."""
    expire = datetime.now(UTC) + timedelta(
        minutes=expires_minutes or settings.access_token_expire_minutes
    )
    payload: dict[str, Any] = {"sub": str(subject), "exp": expire, "type": "access"}
    return jwt.encode(payload, settings.jwt_secret, algorithm=settings.jwt_algorithm)


def decode_access_token(token: str) -> str | None:
    """Return the subject (user id) of a valid token, or ``None`` if invalid."""
    try:
        payload = jwt.decode(token, settings.jwt_secret, algorithms=[settings.jwt_algorithm])
    except JWTError:
        return None
    if payload.get("type") != "access":
        return None
    return payload.get("sub")
